[build]
  command = "bash build.sh"
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "stable"
  PYTHON_VERSION = "3.8"

[[redirects]]
  from = "/supabase-proxy/*"
  to = "https://rxccipqvyrcfpsadgpzp.supabase.co/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
