/// Word bank for Mini Crossword: five-letter words, each with a short clue.
/// Format: WORD|clue. The game builds a fresh grid from these every time.
const List<String> crosswordBank = <String>[
  "ABOUT|Roughly, or concerning",
  "ABOVE|Higher than",
  "ABUJA|Capital city of Nigeria",
  "ACTOR|Performs in plays and films",
  "ADULT|Grown-up person",
  "AFTER|Following in time",
  "ALARM|Loud warning sound",
  "ALBUM|Collection of photos or songs",
  "ALERT|Warning signal",
  "ALIEN|Visitor from another world",
  "AMONG|In the middle of several",
  "ANGEL|Winged heavenly messenger",
  "ANGLE|Where two lines meet",
  "ANGRY|Very annoyed",
  "ANKLE|Joint above the foot",
  "APPLE|Fruit that keeps the doctor away",
  "ARROW|Fired from a bow",
  "ATLAS|Book of maps",
  "BAKER|Makes bread and cakes",
  "BASIC|Simple, at the start",
  "BEACH|Sandy shore by the sea",
  "BEANS|Protein-rich seeds, often eaten with rice",
  "BEAST|Wild animal or monster",
  "BEGIN|Start",
  "BELOW|Lower than",
  "BENIN|Country west of Nigeria",
  "BLACK|Colour of coal",
  "BLEND|Mix together smoothly",
  "BLOOD|Red fluid in the body",
  "BLOOM|Flower in full flower",
  "BOOKS|Things with pages to read",
  "BRAIN|Organ used for thinking",
  "BRASS|Alloy of copper and zinc",
  "BRAVE|Not afraid",
  "BREAD|Baked loaf eaten at breakfast",
  "BROWN|Colour of soil",
  "BRUSH|Used to clean teeth or paint",
  "BUILD|Construct",
  "CABIN|Small wooden house",
  "CABLE|Thick wire",
  "CAMEL|Desert animal with humps",
  "CANDY|Sweet treat for kids",
  "CATCH|Grab a ball in flight",
  "CHAIR|You sit on it",
  "CHART|Table or graph of data",
  "CHEST|Upper front of the body",
  "CHILD|Young boy or girl",
  "CHILL|Cool, or make cold",
  "CHINA|Country with the Great Wall",
  "CLEAN|Free from dirt",
  "CLERK|Office worker who files papers",
  "CLOCK|Shows the time",
  "CLOSE|Shut, or near",
  "CLOUD|White shape floating in the sky",
  "COACH|Trains a sports team",
  "COINS|Metal money",
  "COLOR|Red, blue or green",
  "COMET|Icy body with a glowing tail",
  "COMIC|Funny, or a funny book",
  "COUGH|Noisy burst of air from the lungs",
  "COURT|Where trials are held",
  "CREAM|Thick part of milk",
  "CRIME|Act punishable by law",
  "CROPS|Plants grown by farmers",
  "CROWN|Worn on a monarch's head",
  "DAILY|Every day",
  "DAIRY|Milk, cheese and butter group",
  "DAISY|Small white flower with a yellow centre",
  "DANCE|Move to the rhythm",
  "DIRTY|Not clean",
  "DOZEN|Twelve",
  "DREAM|Pictures in the mind while sleeping",
  "DRUMS|Beaten to keep the beat",
  "EAGLE|Large bird of prey",
  "EARLY|Before the expected time",
  "EARTH|Our planet",
  "EGYPT|Land of the pyramids",
  "EIGHT|Number after seven",
  "ELBOW|Joint in the middle of the arm",
  "EMAIL|Message sent over the internet",
  "ENTER|Come in",
  "ESSAY|Short piece of writing on a topic",
  "EVERY|Each one",
  "EXAMS|Tests at the end of term",
  "EXTRA|More than needed",
  "FAIRY|Tiny magical winged creature",
  "FALSE|Not true",
  "FENCE|Barrier around a garden",
  "FEVER|High body temperature",
  "FIELD|Open land for farming or playing",
  "FINAL|Last",
  "FIRST|Number one",
  "FLAME|Hot glowing part of a fire",
  "FLOOR|The surface you walk on indoors",
  "FLOUR|Powder used to bake bread",
  "FLUTE|Wind instrument you blow across",
  "FORCE|A push or pull",
  "FRAME|Border around a picture",
  "FRESH|Newly made or picked",
  "FROST|Thin ice on cold mornings",
  "GHANA|West African country on the Gulf of Guinea",
  "GHOST|Spooky spirit",
  "GIANT|Enormous being from fairy tales",
  "GLASS|You drink from it, and it breaks",
  "GLOBE|Round model of the Earth",
  "GOATS|Farm animals that bleat and chew",
  "GRADE|School class level or mark",
  "GRAPE|Small fruit that makes wine",
  "GRAPH|Diagram showing data",
  "GRASS|Green lawn cover",
  "GREEN|Colour of grass",
  "GRILL|Cook over an open flame",
  "GUARD|Protects people or places",
  "GUAVA|Tropical fruit with pink flesh",
  "HAPPY|Feeling joy",
  "HAUSA|Major language of northern Nigeria",
  "HEART|Organ that pumps blood",
  "HEAVY|Hard to lift",
  "HELLO|Greeting",
  "HONEY|Sweet food made by bees",
  "HONOR|Great respect",
  "HORSE|Animal you can ride",
  "HOTEL|Place to stay on a trip",
  "HOUSE|Place where a family lives",
  "HUMOR|Quality of being funny",
  "INDIA|Country with the Taj Mahal",
  "INNER|On the inside",
  "INPUT|Data fed into a computer",
  "ITALY|Boot-shaped European country",
  "JUDGE|Decides cases in court",
  "KENYA|East African country, capital Nairobi",
  "KNIFE|Used for cutting food",
  "KOALA|Australian animal that eats eucalyptus",
  "LAGOS|Nigeria's biggest city",
  "LARGE|Big",
  "LASER|Narrow beam of intense light",
  "LATER|After some time",
  "LATIN|Ancient language of Rome",
  "LAUGH|Sound of amusement",
  "LEARN|Gain new knowledge",
  "LEMON|Sour yellow fruit",
  "LEVEL|Flat, or a stage in a game",
  "LIGHT|Opposite of dark",
  "LOGIC|Reasoning",
  "LUNCH|Midday meal",
  "MAGIC|Tricks that seem impossible",
  "MAIZE|Corn",
  "MANGO|Sweet tropical fruit with a big seed",
  "MATCH|Game between two teams",
  "MATHS|Numbers subject, British style",
  "MAYOR|Head of a city council",
  "MEDAL|Awarded to a winner",
  "MELON|Large juicy fruit with seeds",
  "METAL|Iron, gold and copper are this",
  "MODEL|Small copy of something",
  "MONEY|What you spend to buy things",
  "MONTH|About 30 days",
  "MOTOR|Engine that makes things move",
  "MOUSE|Small rodent that squeaks",
  "MOVIE|Film",
  "MUSIC|Songs and melodies",
  "NAIRA|Nigeria's currency",
  "NEVER|Not at any time",
  "NIECE|Your brother's daughter",
  "NIGER|Big West African river and country",
  "NIGHT|When the moon shines",
  "NOISE|Loud unpleasant sound",
  "NOVEL|Long fictional book",
  "NURSE|Cares for patients",
  "OCEAN|Huge body of salt water",
  "OFTEN|Many times",
  "ONION|Vegetable that makes you cry",
  "ORBIT|Path of a planet around the sun",
  "OTHER|Different one",
  "OTTER|Playful river animal",
  "OUTER|On the outside",
  "PAINT|Colored liquid for walls",
  "PANDA|Black and white bear from China",
  "PAPER|Made from wood pulp, you write on it",
  "PARTY|Gathering with music and fun",
  "PASTA|Italian noodles",
  "PEACE|Absence of war",
  "PEACH|Fuzzy fruit with a stone",
  "PETAL|Colourful part of a flower",
  "PHONE|Used to call people",
  "PHOTO|Picture taken with a camera",
  "PIANO|Keyboard instrument",
  "PILOT|Flies an aircraft",
  "PIXEL|Tiny dot on a screen",
  "PLAIN|Flat land, or simple",
  "PLANE|Flies in the sky",
  "PLANT|Living thing that grows from soil",
  "PLATE|Dish you eat from",
  "POEMS|Verses that may rhyme",
  "PORCH|Covered entrance to a house",
  "POWER|Energy or strength",
  "PRICE|What something costs",
  "PRIME|Number with only two factors",
  "PRINT|Press text onto paper",
  "PRIZE|Reward for winning",
  "PUPIL|Student at school",
  "QUEEN|Female ruler",
  "QUIET|Making little noise",
  "RADIO|Broadcasts music and news",
  "RAINY|Wet with falling drops",
  "RAISE|Lift up",
  "RATIO|Comparison of two quantities",
  "RHINO|Horned beast of the savanna",
  "RIGHT|Correct",
  "RISKY|Likely to cause harm",
  "RIVER|Large stream flowing to the sea",
  "ROAST|Cook in an oven",
  "ROBOT|Machine that follows programmed tasks",
  "ROUTE|Way from one place to another",
  "ROYAL|Of a king or queen",
  "RULES|Guidelines to follow",
  "SALAD|Dish of raw vegetables",
  "SANDY|Covered with tiny grains of rock",
  "SCORE|Points in a game",
  "SCOUT|Boy or girl who learns outdoor skills",
  "SHAPE|Form or outline",
  "SHARE|Give part to others",
  "SHARK|Fish with sharp teeth and a fin",
  "SHEEP|Woolly farm animal",
  "SHINY|Bright and reflecting light",
  "SHOOT|Fire at a target",
  "SHORT|Not tall",
  "SKATE|Glide on ice or wheels",
  "SKULL|Bones protecting the brain",
  "SLEEP|Rest with eyes closed",
  "SMALL|Little",
  "SMILE|Happy expression on a face",
  "SMOKE|Grey cloud from a fire",
  "SNAKE|Slithering reptile",
  "SOLAR|Relating to the sun",
  "SOLVE|Find the answer to",
  "SORRY|What you say after a mistake",
  "SOUND|What you hear",
  "SPACE|The universe beyond Earth",
  "SPAIN|European country, capital Madrid",
  "SPEAR|Long pole with a pointed tip",
  "SPEED|How fast something moves",
  "SPELL|Say the letters of a word in order",
  "SPICY|Hot with pepper",
  "SPOON|Used to eat soup",
  "SPORT|Football or tennis, for example",
  "STAGE|Platform for performers",
  "STARS|Twinkle in the night sky",
  "START|Begin",
  "STEAM|Water vapour",
  "STEEL|Strong alloy of iron",
  "STONE|Small rock",
  "STORE|Shop",
  "STORM|Violent weather with thunder",
  "STORY|Tale with a beginning and an end",
  "STUDY|Read to prepare for a test",
  "SUDAN|African country south of Egypt",
  "SUGAR|Sweet white crystals",
  "SUNNY|Bright with sunshine",
  "SWEAT|Salty drops on the skin when hot",
  "SWEET|Sugary",
  "SWORD|Blade carried by a knight",
  "TABLE|Piece of furniture with a flat top",
  "TEACH|Help others learn",
  "TEETH|Used for chewing",
  "THANK|Express gratitude to",
  "THIEF|Person who steals",
  "THIRD|Between second and fourth",
  "THROW|Hurl through the air",
  "THUMB|Short digit of the hand",
  "TIGER|Big striped cat",
  "TOAST|Browned bread slices",
  "TODAY|This very day",
  "TOTAL|The whole sum",
  "TOWER|Tall narrow building",
  "TRACK|Course for running",
  "TRADE|Buy and sell goods",
  "TRAIL|Path through the countryside",
  "TRAIN|Runs on rails",
  "TREAT|Special something nice to eat",
  "TRUCK|Large vehicle for carrying goods",
  "TRUST|Firm belief in someone",
  "TRUTH|The real facts",
  "TUTOR|Private teacher",
  "TWICE|Two times",
  "UNCLE|Your parent's brother",
  "UNDER|Beneath",
  "UNITY|Being together as one",
  "UPPER|Higher in position",
  "VIDEO|Moving pictures recorded",
  "VISIT|Go to see someone",
  "VOICE|What you speak with",
  "WATCH|Worn on the wrist to tell time",
  "WATER|Clear liquid we drink",
  "WHALE|Biggest animal in the sea",
  "WHEEL|Round part that turns",
  "WHITE|Colour of snow",
  "WINDY|With strong breezes",
  "WITCH|Fairy-tale woman with a broomstick",
  "WORDS|Units of language",
  "WORLD|The whole planet and its people",
  "WORSE|Less good than before",
  "WRITE|Put words on paper",
  "WRONG|Incorrect",
  "YOUNG|Not old",
  "ZEBRA|Striped African animal",
];
