// ============================================================
// GACOM: Import 723 users via Supabase Admin API
// ============================================================
// HOW TO RUN IN YOUR GITHUB CODESPACE:
//   1. npm install @supabase/supabase-js
//   2. Set your SUPABASE_SERVICE_ROLE_KEY (from Supabase Dashboard)
//      Dashboard → Settings → API → service_role (secret key)
//   3. node import_users.js
//
// Users are created with email_confirm=true so they don't need
// to verify email — they just need to use Forgot Password.
// ============================================================

const { createClient } = require('@supabase/supabase-js');

const SUPABASE_URL = 'https://rxccipqvyrcfpsadgpzp.supabase.co';
// Get this from Supabase Dashboard → Settings → API → service_role key
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || 'YOUR_SERVICE_ROLE_KEY_HERE';

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
  auth: { autoRefreshToken: false, persistSession: false }
});

const users = [
  { email: "kehindealaka15.acl@gmail.com", username: "kehindealaka15acl", display_name: "Kehindealaka Acl" },
  { email: "nuhunicholas23@gmail.com", username: "nuhunicholas23", display_name: "Nuhunicholas" },
  { email: "immaculateumeh70@gmail.com", username: "immaculateumeh70", display_name: "Immaculateumeh" },
  { email: "nifemiadesanya5006@gmail.com", username: "nifemiadesanya5006", display_name: "Nifemiadesanya" },
  { email: "nurudeeny014@gmail.com", username: "nurudeeny014", display_name: "Nurudeeny" },
  { email: "oshearuvie826@gmail.com", username: "oshearuvie826", display_name: "Oshearuvie" },
  { email: "ibsdaone2@gmail.com", username: "ibsdaone2", display_name: "Ibsdaone" },
  { email: "para090645@gmail.com", username: "para090645", display_name: "Para" },
  { email: "shogunleayomide15@gmail.com", username: "shogunleayomide15", display_name: "Ayomide Shogunle" },
  { email: "ayeeyshababubabu@gmail.com", username: "ayeeyshababubabu", display_name: "Ayeeyshababubabu" },
  { email: "babangidafaizat2021@gmail.com", username: "babangidafaizat2021", display_name: "Babangidafaizat" },
  { email: "udoetoks@gmail.com", username: "udoetoks", display_name: "Udoetoks" },
  { email: "basseychinecheremdaniel44@gmail.com", username: "basseychinecheremdaniel44", display_name: "Basseychinecheremdaniel" },
  { email: "theprinceof9@gmail.com", username: "theprinceof9", display_name: "Odunayo Bukola-Balogun" },
  { email: "aliyuinuwa20@gmail.com", username: "aliyuinuwa20", display_name: "Aliyuinuwa" },
  { email: "yahuzaalmajir2@gmail.com", username: "yahuzaalmajir2", display_name: "Yahuzaalmajir" },
  { email: "125asdrea@gmail.com", username: "125asdrea", display_name: "James Chris" },
  { email: "tamswellbb@gmail.com", username: "tamswellbb", display_name: "Tamswellbb" },
  { email: "tunrayob4@gmail.com", username: "tunrayob4", display_name: "Tunrayob" },
  { email: "melvinprince78@gmail.com", username: "melvinprince78", display_name: "Melvinprince" },
  { email: "kellwise508@gmail.com", username: "kellwise508", display_name: "Kellwise" },
  { email: "priscillaodutolu@gmail.com", username: "priscillaodutolu", display_name: "Priscillaodutolu" },
  { email: "isiaqsekinat4@gmail.com", username: "isiaqsekinat4", display_name: "Isiaqsekinat" },
  { email: "tobynuga@gmail.com", username: "tobynuga", display_name: "Tobynuga" },
  { email: "solentworld000@gmail.com", username: "solentworld000", display_name: "Solentworld" },
  { email: "ifemideonashoga@gmail.com", username: "ifemideonashoga", display_name: "Onashoga Ifemide" },
  { email: "allwellbrownt@gmail.com", username: "allwellbrownt", display_name: "Tamunoibi" },
  { email: "sakaabiola1@gmail.com", username: "sakaabiola1", display_name: "Sakaabiola" },
  { email: "emmanuelthankgod085@gmail.com", username: "emmanuelthankgod085", display_name: "Emmanuelthankgod" },
  { email: "adeyemitoyin837@gmail.com", username: "adeyemitoyin837", display_name: "Adeyemitoyin" },
  { email: "thatboytimiy@gmail.com", username: "thatboytimiy", display_name: "Thatboytimiy" },
  { email: "jemeozor4@gmail.com", username: "jemeozor4", display_name: "Jillian" },
  { email: "favouradesanmi43@gmail.com", username: "favouradesanmi43", display_name: "Favouradesanmi" },
  { email: "heleneffiong082@gmail.com", username: "heleneffiong082", display_name: "Heleneffiong" },
  { email: "oladinno2005@gmail.com", username: "oladinno2005", display_name: "Oladinno" },
  { email: "dejnorthiphone@gmail.com", username: "dejnorthiphone", display_name: "Dejnorthiphone" },
  { email: "smilewrld4@gmail.com", username: "smilewrld4", display_name: "Smile Wrld" },
  { email: "moceret368@morrobel.com", username: "moceret368", display_name: "Moceret" },
  { email: "chigozirimonuoha0@gmail.com", username: "chigozirimonuoha0", display_name: "Chigozirimonuoha" },
  { email: "habiutsifuma@gmail.com", username: "habiutsifuma", display_name: "Habiut Sifuma" },
  { email: "obij56073@gmail.com", username: "obij56073", display_name: "Obij" },
  { email: "aliabdulla5191@gmail.com", username: "aliabdulla5191", display_name: "Aliabdulla" },
  { email: "udohmichael058@gmail.com", username: "udohmichael058", display_name: "Udohmichael" },
  { email: "evilginx303@outlook.com", username: "evilginx303", display_name: "Evilginx" },
  { email: "tripgregs@gmail.com", username: "tripgregs", display_name: "Tripgregs" },
  { email: "tunrab4@gmail.com", username: "tunrab4", display_name: "Tunrab" },
  { email: "mattewpeter819@gmail.com", username: "mattewpeter819", display_name: "Mattewpeter" },
  { email: "ayodeleoluwatosin420@gmail.com", username: "ayodeleoluwatosin420", display_name: "Ayodeleoluwatosin" },
  { email: "dejiniyi127@gmail.com", username: "dejiniyi127", display_name: "Dejiniyi" },
  { email: "somtoemekakalu111@gmail.com", username: "somtoemekakalu111", display_name: "Somtochukwu Kalu" },
  { email: "tallwellbrown@gmail.com", username: "tallwellbrown", display_name: "Tallwellbrown" },
  { email: "jude72916@gmail.com", username: "jude72916", display_name: "Jude" },
  { email: "stephenadekoya19@gmail.com", username: "stephenadekoya19", display_name: "Stephenadekoya" },
  { email: "adesokanmamo@gmail.com", username: "adesokanmamo", display_name: "Adesokanmamo" },
  { email: "banmeketheo@gmail.com", username: "banmeketheo", display_name: "Banmeketheo" },
  { email: "mobtechsincorporate@gmail.com", username: "mobtechsincorporate", display_name: "Mobtechsincorporate" },
  { email: "adeprecious62@gmail.com", username: "adeprecious62", display_name: "Adeprecious" },
  { email: "micdchukwu85@gmail.com", username: "micdchukwu85", display_name: "Micdchukwu" },
  { email: "davidemusella77@gmail.com", username: "davidemusella77", display_name: "Davidemusella" },
  { email: "kahleethjnr@gmail.com", username: "kahleethjnr", display_name: "Kahleethjnr" },
  { email: "baturejunior49@gmail.com", username: "baturejunior49", display_name: "Baturejunior" },
  { email: "samueltella15@gmail.com", username: "samueltella15", display_name: "Samueltella" },
  { email: "oluseyigreatodusote@gmail.com", username: "oluseyigreatodusote", display_name: "Seyi Olusegun" },
  { email: "sanniolumayokun@yahoo.com", username: "sanniolumayokun", display_name: "Sanniolumayokun" },
  { email: "hdjdjsme@gmail.com", username: "hdjdjsme", display_name: "Hdjdjsme" },
  { email: "oyinilesanmi14@gmail.com", username: "oyinilesanmi14", display_name: "Oyin Ilesanmi" },
  { email: "gamezoners719@gmail.com", username: "gamezoners719", display_name: "Gamezoners" },
  { email: "folukeelizabethhoney@gmail.com", username: "folukeelizabethhoney", display_name: "Folukeelizabethhoney" },
  { email: "djucreativity777@gmail.com", username: "djucreativity777", display_name: "Djucreativity" },
  { email: "amanalien2000@gmail.com", username: "amanalien2000", display_name: "Akinjide Akinyemi" },
  { email: "okekebransson@gmail.com", username: "okekebransson", display_name: "Okekebransson" },
  { email: "jakande2005@gmail.com", username: "jakande2005", display_name: "Jakande" },
  { email: "mlifemoshob9@gmail.com", username: "mlifemoshob9", display_name: "Mlifemoshob" },
  { email: "adeyemiqudri64@gmail.com", username: "adeyemiqudri64", display_name: "Adeyemiqudri" },
  { email: "favourobuma@gmail.com", username: "favourobuma", display_name: "Favourobuma" },
  { email: "enochtoye1308@gmail.com", username: "enochtoye1308", display_name: "Enoch Oguntoye" },
  { email: "odekunlefavour93@gmail.com", username: "odekunlefavour93", display_name: "Odekunlefavour" },
  { email: "ayodejiharold@gmail.com", username: "ayodejiharold", display_name: "Ayodejiharold" },
  { email: "gacom.inc@gmail.com", username: "gacominc", display_name: "Biscuit" },
  { email: "autahtafidah@gmali.com", username: "autahtafidah", display_name: "Autahtafidah" },
  { email: "gudetzezggf@gmail.com", username: "gudetzezggf", display_name: "Gudetzezggf" },
  { email: "oluwagbengagbadegesin@gmail.com", username: "oluwagbengagbadegesin", display_name: "Oluwagbengagbadegesin" },
  { email: "adedokunmujeeb97@gmail.com", username: "adedokunmujeeb97", display_name: "Adedokunmujeeb" },
  { email: "demiladeadelekun2020@gmail.com", username: "demiladeadelekun2020", display_name: "Demiladeadelekun" },
  { email: "adebayoadefemi222@gmail.com", username: "adebayoadefemi222", display_name: "Adebayoadefemi" },
  { email: "ilechukwumercy09@gmail.com", username: "ilechukwumercy09", display_name: "Ilechukwu Mercy" },
  { email: "chisomemmanuel2023@gmail.com", username: "chisomemmanuel2023", display_name: "Chisomemmanuel" },
  { email: "tewabechshitem@gmail.com", username: "tewabechshitem", display_name: "Tewabechshitem" },
  { email: "lxggaming2694@gmail.com", username: "lxggaming2694", display_name: "Lxggaming" },
  { email: "amromanoheguono123@gmail.com", username: "amromanoheguono123", display_name: "Amromanoheguono" },
  { email: "forbells29@gmail.com", username: "forbells29", display_name: "Ebuka Oguamanam" },
  { email: "johnraphael481@gmail.com", username: "johnraphael481", display_name: "Johnraphael" },
  { email: "igbaemmanuel655@gmail.com", username: "igbaemmanuel655", display_name: "Igbaemmanuel" },
  { email: "autahtafidah@gmail.com", username: "autahtafidah1", display_name: "Autahtafidah" },
  { email: "akomolafekehinde1999@gmail.com", username: "akomolafekehinde1999", display_name: "Akomolafekehinde" },
  { email: "izalanath3@gmail.com", username: "izalanath3", display_name: "Izalanath" },
  { email: "toluwanimiajiboso03@gmail.com", username: "toluwanimiajiboso03", display_name: "Toluwanimiajiboso" },
  { email: "fathiaidowu16@gmail.com", username: "fathiaidowu16", display_name: "Fathiaidowu" },
  { email: "elouazzania.elhajjam@gmail.com", username: "elouazzaniaelhajjam", display_name: "Elouazzania Elhajjam" },
  { email: "emmablessing1010@gmail.com", username: "emmablessing1010", display_name: "Emmablessing" },
  { email: "chukwuemekauche89@gmail.com", username: "chukwuemekauche89", display_name: "Chukwuemekauche" },
  { email: "counterxmark999@gmail.com", username: "counterxmark999", display_name: "Counterxmark" },
  { email: "israelorubo2@gmail.com", username: "israelorubo2", display_name: "Israelorubo" },
  { email: "anietieben42@gmail.com", username: "anietieben42", display_name: "Anietieben" },
  { email: "azeezsulaimon778@gmail.com", username: "azeezsulaimon778", display_name: "Azeezsulaimon" },
  { email: "mjamiu1301@gmail.com", username: "mjamiu1301", display_name: "Mjamiu" },
  { email: "s89803200@gmail.com", username: "s89803200", display_name: "S" },
  { email: "sirsamjerry@gmail.com", username: "sirsamjerry", display_name: "Sirsamjerry" },
  { email: "abiodunalameem4@gmail.com", username: "abiodunalameem4", display_name: "Abiodunalameem" },
  { email: "aadedayo667@gmail.com", username: "aadedayo667", display_name: "Aadedayo" },
  { email: "emmynba594@gmail.com", username: "emmynba594", display_name: "Emmynba" },
  { email: "mustygee95@gmail.com", username: "mustygee95", display_name: "Mustygee" },
  { email: "andrewsaviour666@gmail.com", username: "andrewsaviour666", display_name: "Andrewsaviour" },
  { email: "yomioyebola11@gmail.com", username: "yomioyebola11", display_name: "Yomioyebola" },
  { email: "lateefabeeb41@gmail.com", username: "lateefabeeb41", display_name: "Lateefabeeb" },
  { email: "wisdomgerald511@gmail.com", username: "wisdomgerald511", display_name: "Wisdomgerald" },
  { email: "tobadare06@gmail.com", username: "tobadare06", display_name: "Tobadare" },
  { email: "eolugbamila@gmail.com", username: "eolugbamila", display_name: "Eolugbamila" },
  { email: "judeonyekwere0123@gmail.com", username: "judeonyekwere0123", display_name: "Judeonyekwere" },
  { email: "justetta123@gmail.com", username: "justetta123", display_name: "Justetta" },
  { email: "afolabimustapha88@gmail.com", username: "afolabimustapha88", display_name: "Afolabimustapha" },
  { email: "kingdihak@gmail.com", username: "kingdihak", display_name: "Kingdihak" },
  { email: "ekureonyeka@gmail.com", username: "ekureonyeka", display_name: "Ekureonyeka" },
  { email: "henshawjohnstone@gmail.com", username: "henshawjohnstone", display_name: "Johnstone Henshaw" },
  { email: "sabiulawal084@gmail.com", username: "sabiulawal084", display_name: "Sabiulawal" },
  { email: "ezeonyemaechi123@gmail.com", username: "ezeonyemaechi123", display_name: "Ezeonyemaechi" },
  { email: "obasteezii@gmail.com", username: "obasteezii", display_name: "Obasteezii" },
  { email: "seze1009@gmail.com", username: "seze1009", display_name: "Seze" },
  { email: "ronaldomolaja333@gmail.com", username: "ronaldomolaja333", display_name: "Ronaldomolaja" },
  { email: "okochika2694@gmail.com", username: "okochika2694", display_name: "Okochika" },
  { email: "asuzukelechi481@gmail.com", username: "asuzukelechi481", display_name: "Asuzukelechi" },
  { email: "patrickemma285@gmail.com", username: "patrickemma285", display_name: "Patrickemma" },
  { email: "samueljohnson5214@gmail.com", username: "samueljohnson5214", display_name: "Samueljohnson" },
  { email: "08130343o@gmail.com", username: "08130343o", display_name: "O" },
  { email: "mm7816769@gmail.com", username: "mm7816769", display_name: "Mm" },
  { email: "ifechukwunnalue20@gmail.com", username: "ifechukwunnalue20", display_name: "Ifechukwunnalue" },
  { email: "udochukwuukaiwo@gmail.com", username: "udochukwuukaiwo", display_name: "Udochukwuukaiwo" },
  { email: "nifemibanjoko301@gmail.com", username: "nifemibanjoko301", display_name: "Nifemibanjoko" },
  { email: "irewolesunday49@gmail.com", username: "irewolesunday49", display_name: "Irewolesunday" },
  { email: "starsmvrt@gmail.com", username: "starsmvrt", display_name: "Starsmvrt" },
  { email: "jacobsjaysy@gmail.com", username: "jacobsjaysy", display_name: "Jacobsjaysy" },
  { email: "yourprobot10@gmail.com", username: "yourprobot10", display_name: "Yourprobot" },
  { email: "kekeemma70@gmail.com", username: "kekeemma70", display_name: "Kekeemma" },
  { email: "alaoridwan69@gmail.com", username: "alaoridwan69", display_name: "Alaoridwan" },
  { email: "samuelenyi806@gmail.com", username: "samuelenyi806", display_name: "Samuelenyi" },
  { email: "saviourofonime@yahoo.com", username: "saviourofonime", display_name: "Saviourofonime" },
  { email: "henshawjames17@gmail.com", username: "henshawjames17", display_name: "James" },
  { email: "d04277415@gmail.com", username: "d04277415", display_name: "D" },
  { email: "alexyokocha22@gmail.com", username: "alexyokocha22", display_name: "Alexyokocha" },
  { email: "opatunjidonald@gmail.com", username: "opatunjidonald", display_name: "Opatunjidonald" },
  { email: "zainababdul458@gmail.com", username: "zainababdul458", display_name: "Zainababdul" },
  { email: "oluwalanapraiseemmanuel@gmail.com", username: "oluwalanapraiseemmanuel", display_name: "Oluwalanapraiseemmanuel" },
  { email: "rachaeljeremy135@gmail.com", username: "rachaeljeremy135", display_name: "Rachaeljeremy" },
  { email: "mousavichristine@gmail.com", username: "mousavichristine", display_name: "Mousavichristine" },
  { email: "waynecodm.9@gmail.com", username: "waynecodm9", display_name: "Waynecodm" },
  { email: "phemostiga@gmail.com", username: "phemostiga", display_name: "Phemostiga" },
  { email: "joshuaehi01@gmail.com", username: "joshuaehi01", display_name: "Joshuaehi" },
  { email: "austinechinasa37@gmail.com", username: "austinechinasa37", display_name: "Austinechinasa" },
  { email: "atik@gmail.com", username: "atik", display_name: "Atik" },
  { email: "mejatjohn@gmail.com", username: "mejatjohn", display_name: "Mejatjohn" },
  { email: "jovienloba1@gmail.com", username: "jovienloba1", display_name: "Jovienloba" },
  { email: "ajijagba@gmail.com", username: "ajijagba", display_name: "Ajijagba" },
  { email: "damilaredavid777@gmail.com", username: "damilaredavid777", display_name: "Damilaredavid" },
  { email: "ismeabubakarusman@gmail.com", username: "ismeabubakarusman", display_name: "Ismeabubakarusman" },
  { email: "nnahchidindu0198@gmail.com", username: "nnahchidindu0198", display_name: "Nnahchidindu" },
  { email: "dghreatone17@gmail.com", username: "dghreatone17", display_name: "Dghreatone" },
  { email: "omoniyiopemipo8@gmail.com", username: "omoniyiopemipo8", display_name: "Omoniyiopemipo" },
  { email: "benedictprecious820@gmail.com", username: "benedictprecious820", display_name: "Benedictprecious" },
  { email: "enaikeleomoh@gmail.com", username: "enaikeleomoh", display_name: "Enaikeleomoh" },
  { email: "wurdbest500@gmail.com", username: "wurdbest500", display_name: "Wurdbest" },
  { email: "isrealmary805@gmail.com", username: "isrealmary805", display_name: "Isrealmary" },
  { email: "rajikazeem807@gmail.com", username: "rajikazeem807", display_name: "Rajikazeem" },
  { email: "alegekingsley@gmail.com", username: "alegekingsley", display_name: "Alegekingsley" },
  { email: "damilolacomfort21@gmail.com", username: "damilolacomfort21", display_name: "Damilolacomfort" },
  { email: "fabianmichael073@gmail.com", username: "fabianmichael073", display_name: "Fabianmichael" },
  { email: "onomeutoware@gmail.com", username: "onomeutoware", display_name: "Onomeutoware" },
  { email: "mikebrew988@gmail.com", username: "mikebrew988", display_name: "Mikebrew" },
  { email: "austintreasure20@gmail.com", username: "austintreasure20", display_name: "Austintreasure" },
  { email: "kaluchukwuma993@gmail.com", username: "kaluchukwuma993", display_name: "Kaluchukwuma" },
  { email: "onwubikochikanyem@gmail.com", username: "onwubikochikanyem", display_name: "Onwubikochikanyem" },
  { email: "iadeola046@gmail.com", username: "iadeola046", display_name: "Iadeola" },
  { email: "ayeniabraham59@gmail.com", username: "ayeniabraham59", display_name: "Ayeniabraham" },
  { email: "ajileyedorcas2244@gmail.com", username: "ajileyedorcas2244", display_name: "Ajileyedorcas" },
  { email: "ikechukwuaugustine782@gmail.com", username: "ikechukwuaugustine782", display_name: "Ikechukwuaugustine" },
  { email: "adedayodavis06@gmail.com", username: "adedayodavis06", display_name: "Adedayodavis" },
  { email: "lanzema33@gmail.com", username: "lanzema33", display_name: "Lanzema" },
  { email: "russellsimon602@gmail.com", username: "russellsimon602", display_name: "Russellsimon" },
  { email: "agbasmoses@gmail.com", username: "agbasmoses", display_name: "Agbasmoses" },
  { email: "assalafigumel@gmail.com", username: "assalafigumel", display_name: "Assalafigumel" },
  { email: "akashkevat441@gmail.com", username: "akashkevat441", display_name: "Akashkevat" },
  { email: "nnahvikky@gmail.com", username: "nnahvikky", display_name: "Nnahvikky" },
  { email: "aniekemejerome209@gmail.com", username: "aniekemejerome209", display_name: "Aniekemejerome" },
  { email: "michaelbusari8@gmail.com", username: "michaelbusari8", display_name: "Michaelbusari" },
  { email: "chinecheremumeh9@gmail.com", username: "chinecheremumeh9", display_name: "Chinecheremumeh" },
  { email: "kekeemmanuel70@gmail.com", username: "kekeemmanuel70", display_name: "Kekeemmanuel" },
  { email: "ikeleblossom3@gmail.com", username: "ikeleblossom3", display_name: "Ikeleblossom" },
  { email: "goodluckobasi16@gmail.com", username: "goodluckobasi16", display_name: "Goodluckobasi" },
  { email: "mw434542@gmail.com", username: "mw434542", display_name: "Mw" },
  { email: "lectenmarine@gmail.com", username: "lectenmarine", display_name: "Lectenmarine" },
  { email: "ajibadeemmanuel710@gmail.com", username: "ajibadeemmanuel710", display_name: "Ajibadeemmanuel" },
  { email: "marcusjohnbull52@gmail.com", username: "marcusjohnbull52", display_name: "Marcusjohnbull" },
  { email: "maddyedward96@gmail.com", username: "maddyedward96", display_name: "Maddyedward" },
  { email: "adimavijayjethro@gmail.com", username: "adimavijayjethro", display_name: "Adimavijayjethro" },
  { email: "beastjaw27@gmail.com", username: "beastjaw27", display_name: "Beastjaw" },
  { email: "trustvvera@gmail.com", username: "trustvvera", display_name: "Trustvvera" },
  { email: "abuibrahim8069@gmail.com", username: "abuibrahim8069", display_name: "Abuibrahim" },
  { email: "ebubetony6@gmail.com", username: "ebubetony6", display_name: "Ebubetony" },
  { email: "ahmaddansarai247@gmail.com", username: "ahmaddansarai247", display_name: "Ahmaddansarai" },
  { email: "balogune932@gmail.com", username: "balogune932", display_name: "Balogune" },
  { email: "lovedayuloma59@gmail.com", username: "lovedayuloma59", display_name: "Lovedayuloma" },
  { email: "adzaageedavid03@gmail.com", username: "adzaageedavid03", display_name: "Adzaageedavid" },
  { email: "emmamich56@gmail.com", username: "emmamich56", display_name: "Emmamich" },
  { email: "rufuselijah6704@gmail.com", username: "rufuselijah6704", display_name: "Rufuselijah" },
  { email: "danieladekoya252@gmail.com", username: "danieladekoya252", display_name: "Adekoya Daniel" },
  { email: "michealbenjamincj.234@gmail.com", username: "michealbenjamincj234", display_name: "Michealbenjamincj" },
  { email: "ukponomfon67@gmail.com", username: "ukponomfon67", display_name: "Ukponomfon" },
  { email: "inumidundamilola2020@gmail.com", username: "inumidundamilola2020", display_name: "Inumidundamilola" },
  { email: "rabiusamaila2019@gmail.com", username: "rabiusamaila2019", display_name: "Rabiusamaila" },
  { email: "arizone4005@gmail.com", username: "arizone4005", display_name: "Arizone" },
  { email: "ceciliaiornumbe003@gmail.com", username: "ceciliaiornumbe003", display_name: "Ceciliaiornumbe" },
  { email: "akanderokeeb4@gmail.com", username: "akanderokeeb4", display_name: "Akanderokeeb" },
  { email: "ogayiozioma588@gmail.com", username: "ogayiozioma588", display_name: "Ogayiozioma" },
  { email: "ekenea368@gmail.com", username: "ekenea368", display_name: "Ekenea" },
  { email: "hallirulawallawal@gmail.com", username: "hallirulawallawal", display_name: "Hallirulawallawal" },
  { email: "putellas02@gmail.com", username: "putellas02", display_name: "Putellas" },
  { email: "adekanmipeace9@gmail.com", username: "adekanmipeace9", display_name: "Adekanmipeace" },
  { email: "lawrenceoluwadarasimi334@gmail.com", username: "lawrenceoluwadarasimi334", display_name: "Lawrenceoluwadarasimi" },
  { email: "yahayaharuna6222@gmail.com", username: "yahayaharuna6222", display_name: "Yahayaharuna" },
  { email: "bamgboyeoladapo2@gmail.com", username: "bamgboyeoladapo2", display_name: "Bamgboyeoladapo" },
  { email: "praisechukwujama23@gmail.com", username: "praisechukwujama23", display_name: "Praisechukwujama" },
  { email: "babalolatomiwa2005@gmail.com", username: "babalolatomiwa2005", display_name: "Babalolatomiwa" },
  { email: "akeembiobaku24@gmail.com", username: "akeembiobaku24", display_name: "Akeembiobaku" },
  { email: "marcellinusmoses6@gmail.com", username: "marcellinusmoses6", display_name: "Marcellinusmoses" },
  { email: "fortuneakinyemi29@gmail.com", username: "fortuneakinyemi29", display_name: "Fortuneakinyemi" },
  { email: "ubongabasiekerete4@gmail.com", username: "ubongabasiekerete4", display_name: "Ubongabasiekerete" },
  { email: "zannahbahulama01@gmail.com", username: "zannahbahulama01", display_name: "Zannahbahulama" },
  { email: "gyungokadonog@gmail.com", username: "gyungokadonog", display_name: "Gyungokadonog" },
  { email: "itzliyoung@gmail.com", username: "itzliyoung", display_name: "Itzliyoung" },
  { email: "okeziewisdom782@gmail.com", username: "okeziewisdom782", display_name: "Okeziewisdom" },
  { email: "mjamiuozovehe@gmail.com", username: "mjamiuozovehe", display_name: "Jamiu Muhammed" },
  { email: "seun.caret@gmail.com", username: "seuncaret", display_name: "Seun Caret" },
  { email: "solomonekwe6@gmail.com", username: "solomonekwe6", display_name: "Solomonekwe" },
  { email: "ralphhmk47@gmail.com", username: "ralphhmk47", display_name: "Ralphhmk" },
  { email: "jeremiahodogwu@gmail.com", username: "jeremiahodogwu", display_name: "Jeremiahodogwu" },
  { email: "uduakimoh43@gmail.com", username: "uduakimoh43", display_name: "Uduakimoh" },
  { email: "maxwellpro87@gmail.com", username: "maxwellpro87", display_name: "Maxwellpro" },
  { email: "ajileyedorcas@rocketmail.com", username: "ajileyedorcas", display_name: "Ajileyedorcas" },
  { email: "zyong3479@gmail.com", username: "zyong3479", display_name: "Zyong" },
  { email: "ofonimes416@gmail.com", username: "ofonimes416", display_name: "Ofonimes" },
  { email: "shadrachinioluwa@gmail.com", username: "shadrachinioluwa", display_name: "Shadrachinioluwa" },
  { email: "akinimole11@gmail.com", username: "akinimole11", display_name: "Akinimole" },
  { email: "rhemajnr05@gmail.com", username: "rhemajnr05", display_name: "Rhemajnr" },
  { email: "adedokunopeyemi715@gmail.com", username: "adedokunopeyemi715", display_name: "Adedokunopeyemi" },
  { email: "chideralincoln174@gmail.com", username: "chideralincoln174", display_name: "Chideralincoln" },
  { email: "hamzataliyu1111@gmail.com", username: "hamzataliyu1111", display_name: "Hamzataliyu" },
  { email: "johnomolola190@gmail.com", username: "johnomolola190", display_name: "Johnomolola" },
  { email: "kelvin69946102@gmail.com", username: "kelvin69946102", display_name: "Kelvin" },
  { email: "chisomobinna409@gmail.com", username: "chisomobinna409", display_name: "Chisomobinna" },
  { email: "deboraholuwatimileyin3@gmail.com", username: "deboraholuwatimileyin3", display_name: "Deboraholuwatimileyin" },
  { email: "smilezinfinite9409@gmail.com", username: "smilezinfinite9409", display_name: "Smilezinfinite" },
  { email: "smallsule050@gmail.com", username: "smallsule050", display_name: "Smallsule" },
  { email: "abdulrahimadamutd@gmail.com", username: "abdulrahimadamutd", display_name: "Abdulrahimadamutd" },
  { email: "adedokunopeyemi815@gmail.com", username: "adedokunopeyemi815", display_name: "Adedokunopeyemi" },
  { email: "promaxmac8@gmail.com", username: "promaxmac8", display_name: "Promaxmac" },
  { email: "marybaby4me@yahoo.com", username: "marybaby4me", display_name: "Marybaby Me" },
  { email: "alabichristy2006@gmail.com", username: "alabichristy2006", display_name: "Alabichristy" },
  { email: "ismailtanko777@gmail.com", username: "ismailtanko777", display_name: "Ismailtanko" },
  { email: "abisolaboluwatife03@gmail.com", username: "abisolaboluwatife03", display_name: "Abisolaboluwatife" },
  { email: "adegbitetolulope2008@gmail.com", username: "adegbitetolulope2008", display_name: "Adegbitetolulope" },
  { email: "topzydee4joke@gmail.com", username: "topzydee4joke", display_name: "Topzydee Joke" },
  { email: "fortuneusoro025@gmail.com", username: "fortuneusoro025", display_name: "Fortuneusoro" },
  { email: "ogizisaviour419@gmail.com", username: "ogizisaviour419", display_name: "Ogizisaviour" },
  { email: "elkamalb@gmail.com", username: "elkamalb", display_name: "Elkamalb" },
  { email: "sabisola0@gmail.com", username: "sabisola0", display_name: "Sabisola" },
  { email: "kaccy121@gmail.com", username: "kaccy121", display_name: "Kaccy" },
  { email: "emmanuelokechukwu.c.2005@gmail.com", username: "emmanuelokechukwuc2005", display_name: "Emmanuelokechukwu C" },
  { email: "funmie0107@gmail.com", username: "funmie0107", display_name: "Funmie" },
  { email: "zimuo0007@gmail.com", username: "zimuo0007", display_name: "Zimuo" },
  { email: "ikechukwu12richard@gmail.com", username: "ikechukwu12richard", display_name: "Ikechukwu Richard" },
  { email: "adeoyeisrael08@gmail.com", username: "adeoyeisrael08", display_name: "Adeoyeisrael" },
  { email: "dblord81@gmail.com", username: "dblord81", display_name: "Dblord" },
  { email: "macualeysamson9@gmail.com", username: "macualeysamson9", display_name: "Macualeysamson" },
  { email: "mustepleazur@gmail.com", username: "mustepleazur", display_name: "Mustepleazur" },
  { email: "franknhodowo@gmail.com", username: "franknhodowo", display_name: "Francis Ugbada" },
  { email: "michaelhorace61@gmail.com", username: "michaelhorace61", display_name: "Michaelhorace" },
  { email: "hamedino224@gmail.com", username: "hamedino224", display_name: "Hamedino" },
  { email: "peacemartins02@gmail.com", username: "peacemartins02", display_name: "Peacemartins" },
  { email: "lazekej@gmail.com", username: "lazekej", display_name: "Lazekej" },
  { email: "olayemiheritage890@gmail.com", username: "olayemiheritage890", display_name: "Olayemiheritage" },
  { email: "shehusulaiman616@gmail.com", username: "shehusulaiman616", display_name: "Shehusulaiman" },
  { email: "adebimpeshittu59@gmail.com", username: "adebimpeshittu59", display_name: "Adebimpeshittu" },
  { email: "tivlumun619@gmail.com", username: "tivlumun619", display_name: "Tivlumun" },
  { email: "mfonakpan975@gmail.com", username: "mfonakpan975", display_name: "Mfonakpan" },
  { email: "osinachinwokocha205@gmail.com", username: "osinachinwokocha205", display_name: "Osinachinwokocha" },
  { email: "hauwayakubujoseph@gmail.com", username: "hauwayakubujoseph", display_name: "Hauwayakubujoseph" },
  { email: "akpanukpono17@gmail.com", username: "akpanukpono17", display_name: "Akpanukpono" },
  { email: "emmanuelakinyode9@gmail.com", username: "emmanuelakinyode9", display_name: "Emmanuelakinyode" },
  { email: "abbankhadijajahun@gmail.com", username: "abbankhadijajahun", display_name: "Abbankhadijajahun" },
  { email: "madallairmiya5@gmail.com", username: "madallairmiya5", display_name: "Madallairmiya" },
  { email: "moh.danlamee@gmail.com", username: "mohdanlamee", display_name: "Moh Danlamee" },
  { email: "muhammadbjibril06@gmail.com", username: "muhammadbjibril06", display_name: "Muhammadbjibril" },
  { email: "brightakinmulewo@gmail.com", username: "brightakinmulewo", display_name: "Brightakinmulewo" },
  { email: "okekep835@gmail.com", username: "okekep835", display_name: "Paul Okeke" },
  { email: "mostunderratedtiger@gmail.com", username: "mostunderratedtiger", display_name: "Saheed Shobanjo" },
  { email: "opeogunadegbola3@gmail.com", username: "opeogunadegbola3", display_name: "Opeogunadegbola" },
  { email: "samadhorpheyhemhi@gmail.com", username: "samadhorpheyhemhi", display_name: "Samadhorpheyhemhi" },
  { email: "ayoadedaniel02@gmail.com", username: "ayoadedaniel02", display_name: "Ayoadedaniel" },
  { email: "kkukoyirapheal@gmail.com", username: "kkukoyirapheal", display_name: "Kkukoyirapheal" },
  { email: "shittusulaiman00@gmail.com", username: "shittusulaiman00", display_name: "Shittusulaiman" },
  { email: "alufuokennneth@gmail.com", username: "alufuokennneth", display_name: "Alufuokennneth" },
  { email: "funshothaoban@gmail.com", username: "funshothaoban", display_name: "Funshothaoban" },
  { email: "jedthebeloved@gmail.com", username: "jedthebeloved", display_name: "Joseph Nwobodo" },
  { email: "tjengine2022@gmail.com", username: "tjengine2022", display_name: "Tjengine" },
  { email: "collinsokpara06@gmail.com", username: "collinsokpara06", display_name: "Collinsokpara" },
  { email: "nnamso65@gmail.com", username: "nnamso65", display_name: "Nnamso" },
  { email: "dokuboprecious33@gmail.com", username: "dokuboprecious33", display_name: "Good luck Dokubo" },
  { email: "samueloladunjoye4@gmail.com", username: "samueloladunjoye4", display_name: "Samueloladunjoye" },
  { email: "adebanwoomogbolahan70@gmail.com", username: "adebanwoomogbolahan70", display_name: "Gbolahan Adebanwo" },
  { email: "akintomiwaogundeyi@gmail.com", username: "akintomiwaogundeyi", display_name: "Akintomiwaogundeyi" },
  { email: "darasimiadebanjo28@gmail.com", username: "darasimiadebanjo28", display_name: "Darasimiadebanjo" },
  { email: "khamilaherominah@gmail.com", username: "khamilaherominah", display_name: "Khamilaherominah" },
  { email: "thegaminghubgacom@gmail.com", username: "thegaminghubgacom", display_name: "thegaminghub" },
  { email: "kelechivivian662@gmail.com", username: "kelechivivian662", display_name: "Kelechivivian" },
  { email: "baloguntaiwo0001@gmail.com", username: "baloguntaiwo0001", display_name: "Baloguntaiwo" },
  { email: "ohejuwachristian@gmail.com", username: "ohejuwachristian", display_name: "Ohejuwachristian" },
  { email: "calebaderoju@gmail.com", username: "calebaderoju", display_name: "Calebaderoju" },
  { email: "ibrahimsaidu034@gmail.com", username: "ibrahimsaidu034", display_name: "Ibrahimsaidu" },
  { email: "emmaboss4000@gmail.com", username: "emmaboss4000", display_name: "Emmaboss" },
  { email: "eshorgold@gmail.com", username: "eshorgold", display_name: "Eshorgold" },
  { email: "babyuk019@gmail.com", username: "babyuk019", display_name: "Babyuk" },
  { email: "olanrewajugbolahan321@gmail.com", username: "olanrewajugbolahan321", display_name: "Olanrewajugbolahan" },
  { email: "deborahobodoechi@gmail.com", username: "deborahobodoechi", display_name: "Deborahobodoechi" },
  { email: "umehvictor00@gmail.com", username: "umehvictor00", display_name: "Umehvictor" },
  { email: "erictimi222@gmail.com", username: "erictimi222", display_name: "Eric Timilehin" },
  { email: "seanyodafe@gmail.com", username: "seanyodafe", display_name: "Seanyodafe" },
  { email: "oladewinola@gmail.com", username: "oladewinola", display_name: "Oladewinola" },
  { email: "oladejih6470@gmail.com", username: "oladejih6470", display_name: "Oladejih" },
  { email: "ckennetizu@gmail.com", username: "ckennetizu", display_name: "Ckennetizu" },
  { email: "pelumi97@protonmail.com", username: "pelumi97", display_name: "Pelumi" },
  { email: "biensandra438@gmail.com", username: "biensandra438", display_name: "Biensandra" },
  { email: "emmanuelchristian2775@gmail.com", username: "emmanuelchristian2775", display_name: "Emmanuelchristian" },
  { email: "fawazadebayo05@gmail.com", username: "fawazadebayo05", display_name: "Fawazadebayo" },
  { email: "isaacarsan@gmail.com", username: "isaacarsan", display_name: "Isaacarsan" },
  { email: "osayimwen.uwamose@gmail.com", username: "osayimwenuwamose", display_name: "Osayimwen Uwamose" },
  { email: "iboroaugustus@gmail.com", username: "iboroaugustus", display_name: "Iboroaugustus" },
  { email: "nanakwame4245@gmail.com", username: "nanakwame4245", display_name: "Nanakwame" },
  { email: "victorgodwin0008@gmail.com", username: "victorgodwin0008", display_name: "Victorgodwin" },
  { email: "twinkletrend66@gmail.com", username: "twinkletrend66", display_name: "Twinkletrend" },
  { email: "olarongbedelight141@gmail.com", username: "olarongbedelight141", display_name: "Olarongbedelight" },
  { email: "olowoyeyecomfort2001@gmail.com", username: "olowoyeyecomfort2001", display_name: "Olowoyeyecomfort" },
  { email: "ayomayowa898@gmail.com", username: "ayomayowa898", display_name: "Ayomayowa" },
  { email: "telly00133@gmail.com", username: "telly00133", display_name: "Telly" },
  { email: "iavenbua@gmail.com", username: "iavenbua", display_name: "Iavenbua" },
  { email: "wonderfulalabi028@gmail.com", username: "wonderfulalabi028", display_name: "Wonderfulalabi" },
  { email: "joyarayi22@gmail.com", username: "joyarayi22", display_name: "Joyarayi" },
  { email: "noelnoemzy@gmail.com", username: "noelnoemzy", display_name: "Noel Goodluck" },
  { email: "francisayokunlesunday@gmail.com", username: "francisayokunlesunday", display_name: "Francisayokunlesunday" },
  { email: "ahmedopeyemi2000@gmail.com", username: "ahmedopeyemi2000", display_name: "Ahmedopeyemi" },
  { email: "segunwilliams09@gmail.com", username: "segunwilliams09", display_name: "Segunwilliams" },
  { email: "arababobola9@gmail.com", username: "arababobola9", display_name: "Araba Adebobola" },
  { email: "aninopayeboye@gmail.com", username: "aninopayeboye", display_name: "Aninopayeboye" },
  { email: "caasi9092@gmail.com", username: "caasi9092", display_name: "Isaac Ogunrinola" },
  { email: "nifemidan567@gmail.com", username: "nifemidan567", display_name: "NIFEMI DANIEL" },
  { email: "oguntoyinbofatai422@gmail.com", username: "oguntoyinbofatai422", display_name: "Oguntoyinbofatai" },
  { email: "okaform454@gmail.com", username: "okaform454", display_name: "Okaform" },
  { email: "abellamaria8610@gmail.com", username: "abellamaria8610", display_name: "Abellamaria" },
  { email: "arababobola@gmail.com", username: "arababobola", display_name: "Arababobola" },
  { email: "roseclarkson67@gmail.com", username: "roseclarkson67", display_name: "Roseclarkson" },
  { email: "chukwumarema529@gmail.com", username: "chukwumarema529", display_name: "Chukwumarema" },
  { email: "idemudiah621@gmail.com", username: "idemudiah621", display_name: "Idemudia" },
  { email: "dylanrooney619@gmail.com", username: "dylanrooney619", display_name: "Dylanrooney" },
  { email: "madumelubouch@gmail.com", username: "madumelubouch", display_name: "Madumelubouch" },
  { email: "abuolotuemmanuel@gmail.com", username: "abuolotuemmanuel", display_name: "Abuolotuemmanuel" },
  { email: "martadeen01@gmail.com", username: "martadeen01", display_name: "Martadeen" },
  { email: "2buzoremma@gmail.com", username: "2buzoremma", display_name: "Buzoremma" },
  { email: "godfryben7@gmail.com", username: "godfryben7", display_name: "Godfryben" },
  { email: "nisaiah658@gmail.com", username: "nisaiah658", display_name: "Nisaiah" },
  { email: "noelgoodluck5@gmail.com", username: "noelgoodluck5", display_name: "Noel Goodluck" },
  { email: "benjaminorike7@gmail.com", username: "benjaminorike7", display_name: "Benjaminorike" },
  { email: "opemiposowemimo@gmail.com", username: "opemiposowemimo", display_name: "Opemiposowemimo" },
  { email: "mbeludaniel@gmail.com", username: "mbeludaniel", display_name: "Mbeludaniel" },
  { email: "darlingtonariogho@gmail.com", username: "darlingtonariogho", display_name: "Darlingtonariogho" },
  { email: "ayubsonchristopher@gmail.com", username: "ayubsonchristopher", display_name: "Ayubsonchristopher" },
  { email: "samuelhabib5050@gmail.com", username: "samuelhabib5050", display_name: "Samuelhabib" },
  { email: "akinrotimitemitope92@gmail.com", username: "akinrotimitemitope92", display_name: "Akinrotimitemitope" },
  { email: "psalmod3@gmail.com", username: "psalmod3", display_name: "Psalmod" },
  { email: "elissamelissa87@gmail.com", username: "elissamelissa87", display_name: "Elissamelissa" },
  { email: "ahmadkrisht2010@gmail.com", username: "ahmadkrisht2010", display_name: "Ahmad Krisht" },
  { email: "maliktosho27@gmail.com", username: "maliktosho27", display_name: "Maliktosho" },
  { email: "mitchellolisehmedua@gmail.com", username: "mitchellolisehmedua", display_name: "Mitchellolisehmedua" },
  { email: "opemipofasanya08@gmail.com", username: "opemipofasanya08", display_name: "Opemipo Fasanya" },
  { email: "joeleneojo2019@gmail.com", username: "joeleneojo2019", display_name: "Joeleneojo" },
  { email: "timkatsilas@gmail.com", username: "timkatsilas", display_name: "Timkatsilas" },
  { email: "greatlifeinchrist4eva@gmail.com", username: "greatlifeinchrist4eva", display_name: "Adeoluwa Adetilewa" },
  { email: "odigiedivinefavour@gmail.com", username: "odigiedivinefavour", display_name: "Odigiedivinefavour" },
  { email: "omonayajocitn@gmail.com", username: "omonayajocitn", display_name: "Omonayajocitn" },
  { email: "ugonnayaugonna835@gmail.com", username: "ugonnayaugonna835", display_name: "Ugonnayaugonna" },
  { email: "dn5058356@gmail.com", username: "dn5058356", display_name: "Dn" },
  { email: "pducer10@gmail.com", username: "pducer10", display_name: "Pducer" },
  { email: "henryfreeman2006@gmail.com", username: "henryfreeman2006", display_name: "Henryfreeman" },
  { email: "moneymaann07@gmail.com", username: "moneymaann07", display_name: "Roman Silver" },
  { email: "adeboyekally27@gmail.com", username: "adeboyekally27", display_name: "Khally Khally" },
  { email: "goodnewsibrahim299@gmail.com", username: "goodnewsibrahim299", display_name: "Ibrahim Goodnews" },
  { email: "adamgegele79@gmail.com", username: "adamgegele79", display_name: "Adam Gegele" },
  { email: "kelanijohn040@gmail.com", username: "kelanijohn040", display_name: "John Kelani" },
  { email: "danieliheanacho2021@gmail.com", username: "danieliheanacho2021", display_name: "Daisuke Hax" },
  { email: "tochexgaming@gmail.com", username: "tochexgaming", display_name: "Tochex Games" },
  { email: "idibiajoseph06@gmail.com", username: "idibiajoseph06", display_name: "Joseph Idibia" },
  { email: "fagbenromubarak7@gmail.com", username: "fagbenromubarak7", display_name: "Fagbenro Mubarak" },
  { email: "michaelchidebere87@gmail.com", username: "michaelchidebere87", display_name: "Danny Cross" },
  { email: "ahmedfizane1@gmail.com", username: "ahmedfizane1", display_name: "Ahmedfizane" },
  { email: "abrahamayomide97@gmail.com", username: "abrahamayomide97", display_name: "Abrahamayomide" },
  { email: "chris16nv@gmail.com", username: "chris16nv", display_name: "Chris Etim" },
  { email: "maltechtics@gmail.com", username: "maltechtics", display_name: "Abdulmalik Imuekemhe" },
  { email: "wisdomchukwudi07042@gmail.com", username: "wisdomchukwudi07042", display_name: "Emmanuel Aina" },
  { email: "arafatabdulmomin7@gmail.com", username: "arafatabdulmomin7", display_name: "Arafatabdulmomin" },
  { email: "fornfk64@gmail.com", username: "fornfk64", display_name: "Nfk Prime" },
  { email: "shalomgeorge0602@gmail.com", username: "shalomgeorge0602", display_name: "Shalom George" },
  { email: "vicnitedigitals@gmail.com", username: "vicnitedigitals", display_name: "Olotu Victor" },
  { email: "okpogoroh@gmail.com", username: "okpogoroh", display_name: "Okpogoro Henry Oghenekvwe" },
  { email: "praise.eze1990@gmail.com", username: "praiseeze1990", display_name: "Praise Eze" },
  { email: "majestydanielgana@gmail.com", username: "majestydanielgana", display_name: "Gana Majesty daniel" },
  { email: "ukpongdavid767@gmail.com", username: "ukpongdavid767", display_name: "Casper DaGremlin" },
  { email: "jmj54798@gmail.com", username: "jmj54798", display_name: "Nafeez Idris" },
  { email: "memoreality9876@gmail.com", username: "memoreality9876", display_name: "Memo Reality" },
  { email: "ajala2277@gmail.com", username: "ajala2277", display_name: "Samuel Ajala" },
  { email: "abdulazeez0906y@gmail.com", username: "abdulazeez0906y", display_name: "Abdulazeez Abdulazeez" },
  { email: "davidtimidamilare22@gmail.com", username: "davidtimidamilare22", display_name: "David Oluwatimilehin" },
  { email: "agboolaokikiola360@gmail.com", username: "agboolaokikiola360", display_name: "Agboola Okiki" },
  { email: "hameedadebisi986@gmail.com", username: "hameedadebisi986", display_name: "Adebisi Hameed" },
  { email: "davidoojaide@gmail.com", username: "davidoojaide", display_name: "Davidoojaide" },
  { email: "vitaliswise105@gmail.com", username: "vitaliswise105", display_name: "Vitaliswise" },
  { email: "okemeking@gmail.com", username: "okemeking", display_name: "Okemeking" },
  { email: "mediamarkart@gmail.com", username: "mediamarkart", display_name: "Mediamarkart" },
  { email: "akanbimichael00@gmail.com", username: "akanbimichael00", display_name: "Akanbi Micheal" },
  { email: "abdullahluwajuwon@gmail.com", username: "abdullahluwajuwon", display_name: "Abdullahluwajuwon" },
  { email: "charlesegwunwoke@gmail.com", username: "charlesegwunwoke", display_name: "Charles Egwunwoke" },
  { email: "lucianyourfada@gmail.com", username: "lucianyourfada", display_name: "Lucian Great" },
  { email: "opeade0203@gmail.com", username: "opeade0203", display_name: "Adeyemi Opeyemi" },
  { email: "pukumakindnessmusa@gmail.com", username: "pukumakindnessmusa", display_name: "Toxic King" },
  { email: "fortetafabianbrakemi@gmail.com", username: "fortetafabianbrakemi", display_name: "Forteta Fabian" },
  { email: "rahimsoriq@gmail.com", username: "rahimsoriq", display_name: "Just a Chillguy" },
  { email: "smiharriet8@gmail.com", username: "smiharriet8", display_name: "Metro Boomer" },
  { email: "shobanjosaidat123@gmail.com", username: "shobanjosaidat123", display_name: "Shobanjosaidat" },
  { email: "oreokeme@gmail.com", username: "oreokeme", display_name: "King Gerald" },
  { email: "abuchichigbu90@gmail.com", username: "abuchichigbu90", display_name: "el Bombocl4t" },
  { email: "adejoc2@gmail.com", username: "adejoc2", display_name: "Christian Adejo" },
  { email: "peteremma049@gmail.com", username: "peteremma049", display_name: "Bishop Minex" },
  { email: "frankbello1512@gmail.com", username: "frankbello1512", display_name: "Frankbello" },
  { email: "youngjohn80090@gmail.com", username: "youngjohn80090", display_name: "Adekunle Israel" },
  { email: "brightduru707@gmail.com", username: "brightduru707", display_name: "Brightduru" },
  { email: "chideraagah4@gmail.com", username: "chideraagah4", display_name: "Agah Isaac" },
  { email: "christopherchristian117@gmail.com", username: "christopherchristian117", display_name: "Christian Christopher" },
  { email: "ojoenoch2022@gmail.com", username: "ojoenoch2022", display_name: "Tunademise Ojo" },
  { email: "spencs5301@gmail.com", username: "spencs5301", display_name: "Spencs" },
  { email: "kollinzwest00@gmail.com", username: "kollinzwest00", display_name: "Kollinzwest" },
  { email: "chukssamuel131@gmail.com", username: "chukssamuel131", display_name: "Chukwuemeka Samuel" },
  { email: "emmykelleharjnr@gmail.com", username: "emmykelleharjnr", display_name: "Kelleher Raphael" },
  { email: "aduniyisamuel@gmail.com", username: "aduniyisamuel", display_name: "Aduniyisamuel" },
  { email: "bunmiadejuyigbe692@gmail.com", username: "bunmiadejuyigbe692", display_name: "Dayo Adegoke" },
  { email: "igneeln288@gmail.com", username: "igneeln288", display_name: "Joshua Campbell" },
  { email: "daudaisaac747@gmail.com", username: "daudaisaac747", display_name: "Daudaisaac" },
  { email: "blessedavreson01@gmail.com", username: "blessedavreson01", display_name: "Avreson Blessed" },
  { email: "emekamoses181@gmail.com", username: "emekamoses181", display_name: "Emekamoses" },
  { email: "habdulhameedsaidu45@gmail.com", username: "habdulhameedsaidu45", display_name: "Saidu Abdulhameed" },
  { email: "henryavreson@gmail.com", username: "henryavreson", display_name: "Henryavreson" },
  { email: "ezihonyedikachukwu@gmail.com", username: "ezihonyedikachukwu", display_name: "Ezih Onyedikachukwu" },
  { email: "berryzapi99@gmail.com", username: "berryzapi99", display_name: "Berry Zapi" },
  { email: "ogunjimivictorv23@gmail.com", username: "ogunjimivictorv23", display_name: "Victor Ogunjimi" },
  { email: "vyrus2468@gmail.com", username: "vyrus2468", display_name: "Victor Adekunle" },
  { email: "ojshedrach@gmail.com", username: "ojshedrach", display_name: "Shedrach Onah" },
  { email: "ayoolajoseph333@gmail.com", username: "ayoolajoseph333", display_name: "Joseph Ayoola" },
  { email: "abdulwasiubasit4@gmail.com", username: "abdulwasiubasit4", display_name: "Abdulwasiubasit" },
  { email: "mortalffhxx@gmail.com", username: "mortalffhxx", display_name: "Mortal FF" },
  { email: "taofeeqshittu63@gmail.com", username: "taofeeqshittu63", display_name: "Shittu Muhammadtaofeeq" },
  { email: "sadiqadavizefarouk24@gmail.com", username: "sadiqadavizefarouk24", display_name: "Farouk Sadiq" },
  { email: "asarikennedy3@gmail.com", username: "asarikennedy3", display_name: "Nb Kenny" },
  { email: "benmaxorons@gmail.com", username: "benmaxorons", display_name: "Benedict Oronsaye" },
  { email: "olukotunjoshua22@gmail.com", username: "olukotunjoshua22", display_name: "Joshua Olukotun" },
  { email: "davidokoccha@gmail.com", username: "davidokoccha", display_name: "David Okocha" },
  { email: "ayobamialmustapha695@gmail.com", username: "ayobamialmustapha695", display_name: "Ayobami Almustapha" },
  { email: "erobijohnpaul@gmail.com", username: "erobijohnpaul", display_name: "Johnpaul Erobi" },
  { email: "fortunekenegharevba@gmail.com", username: "fortunekenegharevba", display_name: "Fortunekenegharevba" },
  { email: "ehimenjeffrey58@gmail.com", username: "ehimenjeffrey58", display_name: "Ehimen Jeffrey" },
  { email: "faridahajagbe@gmail.com", username: "faridahajagbe", display_name: "Faidah Adenike" },
  { email: "grammz2023@gmail.com", username: "grammz2023", display_name: "David Michael" },
  { email: "joek2173@gmail.com", username: "joek2173", display_name: "Adebayo Joseph" },
  { email: "imuzezesamuel@gmail.com", username: "imuzezesamuel", display_name: "Imuzeze Samuel" },
  { email: "docstandardcooperation@gmail.com", username: "docstandardcooperation", display_name: "Daniel Uwakwe" },
  { email: "sammydiamond321@gmail.com", username: "sammydiamond321", display_name: "Samuel Olukorede" },
  { email: "josephojay79@gmail.com", username: "josephojay79", display_name: "Josephojay" },
  { email: "iniceles05@gmail.com", username: "iniceles05", display_name: "Inimfon" },
  { email: "phantomgrimreaper5@gmail.com", username: "phantomgrimreaper5", display_name: "Kiyotaka Ayanokoji" },
  { email: "angels4elisha@gmail.com", username: "angels4elisha", display_name: "Elisha Esaigun" },
  { email: "otabordivine668@gmail.com", username: "otabordivine668", display_name: "Otabor Divine" },
  { email: "samuelomitiran7@gmail.com", username: "samuelomitiran7", display_name: "Samuel Omitiran" },
  { email: "nwosusochi23@gmail.com", username: "nwosusochi23", display_name: "Nwosu Sochima" },
  { email: "princyudoh@gmail.com", username: "princyudoh", display_name: "Madara Uchiha" },
  { email: "joshuaogung@gmail.com", username: "joshuaogung", display_name: "Joshua Ogugbile" },
  { email: "godwillkaliamah@gmail.com", username: "godwillkaliamah", display_name: "God\'sWill Kalu" },
  { email: "georgewillbert915@gmail.com", username: "georgewillbert915", display_name: "Georgewillbert" },
  { email: "onyeckachiemmanuel69@gmail.com", username: "onyeckachiemmanuel69", display_name: "Onyeckachiemmanuel" },
  { email: "abdulbakibello009@gmail.com", username: "abdulbakibello009", display_name: "Abdulbakibello" },
  { email: "ifemhedey0@gmail.com", username: "ifemhedey0", display_name: "Ifemhedey" },
  { email: "soloboda110@gmail.com", username: "soloboda110", display_name: "Soloboda" },
  { email: "okoliemmanuel591@gmail.com", username: "okoliemmanuel591", display_name: "Emmanuel Okoli" },
  { email: "ayamwise123@gmail.com", username: "ayamwise123", display_name: "Ayamwise" },
  { email: "oluwadamilolakoya@gmail.com", username: "oluwadamilolakoya", display_name: "Oluwadamilolakoya" },
  { email: "mazeedfiyinfoluwa@gmail.com", username: "mazeedfiyinfoluwa", display_name: "Mazeedfiyinfoluwa" },
  { email: "fornfk824@gmail.com", username: "fornfk824", display_name: "NFK Prime" },
  { email: "emmatech2204@gmail.com", username: "emmatech2204", display_name: "Emmanuel Kolade" },
  { email: "nnamdim76@gmail.com", username: "nnamdim76", display_name: "Nnamdim" },
  { email: "deneh602@gmail.com", username: "deneh602", display_name: "Deneh" },
  { email: "kingston11112008@gmail.com", username: "kingston11112008", display_name: "Kingston" },
  { email: "yusufboty252@gmail.com", username: "yusufboty252", display_name: "Yusufboty" },
  { email: "egaminghub1@gmail.com", username: "egaminghub1", display_name: "Egaminghub" },
  { email: "princezy903@gmail.com", username: "princezy903", display_name: "Princezy" },
  { email: "creedzilla6@gmail.com", username: "creedzilla6", display_name: "Creedzilla" },
  { email: "jamesstiles1q@gmail.com", username: "jamesstiles1q", display_name: "Jamesstiles Q" },
  { email: "ramadhanyusuf346@gmail.com", username: "ramadhanyusuf346", display_name: "Ramadhanyusuf" },
  { email: "tenipaz120@gmail.com", username: "tenipaz120", display_name: "Tenipaz" },
  { email: "sodiqyinka137@gmail.com", username: "sodiqyinka137", display_name: "Sodiqyinka" },
  { email: "jackdemon966@gmail.com", username: "jackdemon966", display_name: "Jackdemon" },
  { email: "otunbakehinde11@gmail.com", username: "otunbakehinde11", display_name: "Otunbakehinde" },
  { email: "techhonorable2009@gmail.com", username: "techhonorable2009", display_name: "Monday Great Ekele" },
  { email: "oluwatobioyegade22@gmail.com", username: "oluwatobioyegade22", display_name: "Oluwatobioyegade" },
  { email: "isahali040@gmail.com", username: "isahali040", display_name: "Isahali" },
  { email: "abbysax12@gmail.com", username: "abbysax12", display_name: "Abraham Salifu" },
  { email: "okechukwugreat4k@gmail.com", username: "okechukwugreat4k", display_name: "Okechukwugreat K" },
  { email: "chukwundik01@gmail.com", username: "chukwundik01", display_name: "Chukwundik" },
  { email: "rosamccarter49@gmail.com", username: "rosamccarter49", display_name: "Rosamccarter" },
  { email: "matapaandrew01@gmail.com", username: "matapaandrew01", display_name: "Matapaandrew" },
  { email: "olamideawolaja948@gmail.com", username: "olamideawolaja948", display_name: "Olamideawolaja" },
  { email: "tikrennbs@gmail.com", username: "tikrennbs", display_name: "RENN Renn" },
  { email: "eabu2285@gmail.com", username: "eabu2285", display_name: "Emmanuel John" },
  { email: "vcphantom73@gmail.com", username: "vcphantom73", display_name: "Vcphantom" },
  { email: "nandomcherish027@gmail.com", username: "nandomcherish027", display_name: "Nandomcherish" },
  { email: "rufaifatia24434@gmail.com", username: "rufaifatia24434", display_name: "Rufaifatia" },
  { email: "sammytope5@gmail.com", username: "sammytope5", display_name: "Sammytope" },
  { email: "faletiifedolapo@gmail.com", username: "faletiifedolapo", display_name: "Demilade Faleti" },
  { email: "kingezra145@gmail.com", username: "kingezra145", display_name: "Kingezra" },
  { email: "matthewsort61@gmail.com", username: "matthewsort61", display_name: "Matthewsort" },
  { email: "greatedewor89@gmail.com", username: "greatedewor89", display_name: "Greatedewor" },
  { email: "meekman95@gmail.com", username: "meekman95", display_name: "Meekman" },
  { email: "isiomapraise6@gmail.com", username: "isiomapraise6", display_name: "Isiomapraise" },
  { email: "ibukunoluwafemi42@gmail.com", username: "ibukunoluwafemi42", display_name: "ibukun oluwafemi" },
  { email: "ibezimjoy2017@gmail.com", username: "ibezimjoy2017", display_name: "Ibezimjoy" },
  { email: "amaechidaniel112@gmail.com", username: "amaechidaniel112", display_name: "Amaechidaniel" },
  { email: "abdulsalamadio7@gmail.com", username: "abdulsalamadio7", display_name: "Abdulsalamadio" },
  { email: "dakjzkgba@gmail.com", username: "dakjzkgba", display_name: "Dakjzkgba" },
  { email: "juzolaz@gmail.com", username: "juzolaz", display_name: "Juzolaz" },
  { email: "teemysamson144@gmail.com", username: "teemysamson144", display_name: "Teemysamson" },
  { email: "unmaskedcomedy@gmail.com", username: "unmaskedcomedy", display_name: "Unmaskedcomedy" },
  { email: "awoleyeprecious41@gmail.com", username: "awoleyeprecious41", display_name: "Awoleyeprecious" },
  { email: "dariusibekwe1@gmail.com", username: "dariusibekwe1", display_name: "Dariusibekwe" },
  { email: "jareddavies890@gmail.com", username: "jareddavies890", display_name: "Jareddavies" },
  { email: "samuelelewononi@gmail.com", username: "samuelelewononi", display_name: "Samuelelewononi" },
  { email: "sammytope6@gmail.com", username: "sammytope6", display_name: "Sammytope" },
  { email: "boluwatised@gmail.com", username: "boluwatised", display_name: "Boluwatised" },
  { email: "joyibezim31@gmail.com", username: "joyibezim31", display_name: "Joyibezim" },
  { email: "wizzymikky521@gmail.com", username: "wizzymikky521", display_name: "Wisdom Michael" },
  { email: "oghoghorieakpevwe@gmail.com", username: "oghoghorieakpevwe", display_name: "Oghoghorieakpevwe" },
  { email: "akintundeifeoluwa612@gmail.com", username: "akintundeifeoluwa612", display_name: "Akintundeifeoluwa" },
  { email: "roroyoung209@gmail.com", username: "roroyoung209", display_name: "Roroyoung" },
  { email: "thechibozz@gmail.com", username: "thechibozz", display_name: "Thechibozz" },
  { email: "samuelokitor7@gmail.com", username: "samuelokitor7", display_name: "Noob Tiktok" },
  { email: "dinakehinde12@gmail.com", username: "dinakehinde12", display_name: "Kehinde Dina" },
  { email: "silverlord055@gmail.com", username: "silverlord055", display_name: "Silverlord" },
  { email: "dchidesco@gmail.com", username: "dchidesco", display_name: "Dchidesco" },
  { email: "amosisaleye@gmail.com", username: "amosisaleye", display_name: "Amosisaleye" },
  { email: "victoroyebanji39@gmail.com", username: "victoroyebanji39", display_name: "Victoroyebanji" },
  { email: "uchechukwus847@gmail.com", username: "uchechukwus847", display_name: "Samuel Uchechukwu" },
  { email: "sourabhmrfr19@gmail.com", username: "sourabhmrfr19", display_name: "Sourabhmrfr" },
  { email: "muolokwuabuchi@gmail.com", username: "muolokwuabuchi", display_name: "Muolokwuabuchi" },
  { email: "kryelltiger@gmail.com", username: "kryelltiger", display_name: "Kryelltiger" },
  { email: "gabg83226@gmail.com", username: "gabg83226", display_name: "Gabg" },
  { email: "efeahwayievu@gmail.com", username: "efeahwayievu", display_name: "Efeahwayievu" },
  { email: "marvinwilla0@gmail.com", username: "marvinwilla0", display_name: "Marvinwilla" },
  { email: "pelumia602@gmail.com", username: "pelumia602", display_name: "Pelumi Idowu" },
  { email: "lekank331@gmail.com", username: "lekank331", display_name: "Ola Lekzy" },
  { email: "georgealabi568@gmail.com", username: "georgealabi568", display_name: "Georgealabi" },
  { email: "nzubemnwoye@gmail.com", username: "nzubemnwoye", display_name: "Nzubemnwoye" },
  { email: "afolabiayom@gmail.com", username: "afolabiayom", display_name: "Afolabiayom" },
  { email: "tofeyinti89@gmail.com", username: "tofeyinti89", display_name: "Tofeyinti" },
  { email: "michael08153@gmail.com", username: "michael08153", display_name: "Michael Peter" },
  { email: "veersparo@gmail.com", username: "veersparo", display_name: "Veersparo" },
  { email: "chukwuemekaignatius111@gmail.com", username: "chukwuemekaignatius111", display_name: "Chukwuemekaignatius" },
  { email: "danieldamilola494@gmail.com", username: "danieldamilola494", display_name: "Danieldamilola" },
  { email: "ariagiegbeemmanuel@gmail.com", username: "ariagiegbeemmanuel", display_name: "Emmanuel ARIAGIEGBE" },
  { email: "dukehound181@gmail.com", username: "dukehound181", display_name: "Dukehound" },
  { email: "yusufsuleimanezhin@gmail.com", username: "yusufsuleimanezhin", display_name: "Yusufsuleimanezhin" },
  { email: "umaryore08@gmail.com", username: "umaryore08", display_name: "Umaryore" },
  { email: "ibekwedarius45@gmail.com", username: "ibekwedarius45", display_name: "Darius Ibekwe" },
  { email: "wilsonpresley850@gmail.com", username: "wilsonpresley850", display_name: "Wilsonpresley" },
  { email: "enyiaisrael@gmail.com", username: "enyiaisrael", display_name: "Enyiaisrael" },
  { email: "emmanuelsobo99@gmail.com", username: "emmanuelsobo99", display_name: "Emmanuelsobo" },
  { email: "satarbabs23@gmail.com", username: "satarbabs23", display_name: "Satarbabs" },
  { email: "olashinamuhammed22@gmail.com", username: "olashinamuhammed22", display_name: "Olashinamuhammed" },
  { email: "bricksbenjamin61@gmail.com", username: "bricksbenjamin61", display_name: "Bricksbenjamin" },
  { email: "ifechukwuuwagba6@gmail.com", username: "ifechukwuuwagba6", display_name: "Ifechukwu Uwagba" },
  { email: "stanleychika113@gmail.com", username: "stanleychika113", display_name: "Stanleychika" },
  { email: "nicolecopeland001@gmail.com", username: "nicolecopeland001", display_name: "Nicolecopeland" },
  { email: "bertcal37@gmail.com", username: "bertcal37", display_name: "Bertcal" },
  { email: "erosenpai8@gmail.com", username: "erosenpai8", display_name: "Ero Senpai" },
  { email: "beeplaysmlbb@gmail.com", username: "beeplaysmlbb", display_name: "Ibrahim Lawal" },
  { email: "dickydiorpablo@gmail.com", username: "dickydiorpablo", display_name: "Dickydiorpablo" },
  { email: "kohworeuben6@gmail.com", username: "kohworeuben6", display_name: "Kohworeuben" },
  { email: "victoregwuhness@gmail.com", username: "victoregwuhness", display_name: "Victoregwuhness" },
  { email: "omodamwenfelicia6@gmail.com", username: "omodamwenfelicia6", display_name: "Omodamwenfelicia" },
  { email: "anidaniel1832@gmail.com", username: "anidaniel1832", display_name: "Anidaniel" },
  { email: "100eldorado265@gmail.com", username: "100eldorado265", display_name: "El Dorado" },
  { email: "danielikechukwu2012@gmail.com", username: "danielikechukwu2012", display_name: "Daniel Ovat" },
  { email: "rikelmemenezes38@gmail.com", username: "rikelmemenezes38", display_name: "Rikelmemenezes" },
  { email: "dmassaquoi44@gmail.com", username: "dmassaquoi44", display_name: "Dmassaquoi" },
  { email: "floof2580@gmail.com", username: "floof2580", display_name: "Floof" },
  { email: "hadebanjo777@gmail.com", username: "hadebanjo777", display_name: "Hadebanjo" },
  { email: "destruc3803l@gmail.com", username: "destruc3803l", display_name: "Destruc L" },
  { email: "obiokoyedelight@gmail.com", username: "obiokoyedelight", display_name: "Obiokoyedelight" },
  { email: "uchechic33@gmail.com", username: "uchechic33", display_name: "Uchechic" },
  { email: "kelvincharlesnd@gmail.com", username: "kelvincharlesnd", display_name: "Kelvincharlesnd" },
  { email: "mayowabsq28@gmail.com", username: "mayowabsq28", display_name: "Mayowabsq" },
  { email: "jq784040@gmail.com", username: "jq784040", display_name: "Jq" },
  { email: "marjormarineltd@gmail.com", username: "marjormarineltd", display_name: "Marjormarineltd" },
  { email: "emmanuelekigho@gmail.com", username: "emmanuelekigho", display_name: "Emmanuel Ekigho" },
  { email: "princewillanyaogu4@gmail.com", username: "princewillanyaogu4", display_name: "Princewillanyaogu" },
  { email: "babatundeemmanuel8599@gamil.com", username: "babatundeemmanuel8599", display_name: "Babatundeemmanuel" },
  { email: "ilorieniola517@gmail.com", username: "ilorieniola517", display_name: "Ilorieniola" },
  { email: "gideonola2006@gmail.com", username: "gideonola2006", display_name: "Gideon Ola" },
  { email: "okunnua.m@gmail.com", username: "okunnuam", display_name: "Okunnua M" },
  { email: "johnjustice112@gmail.com", username: "johnjustice112", display_name: "Johnjustice" },
  { email: "samuelkolade45@gmail.com", username: "samuelkolade45", display_name: "Samuelkolade" },
  { email: "bernardbakare@gmail.com", username: "bernardbakare", display_name: "Bernardbakare" },
  { email: "agadasunday451@gmail.com", username: "agadasunday451", display_name: "Agada Sunday" },
  { email: "efeturiokeoghene2@gmail.com", username: "efeturiokeoghene2", display_name: "Efeturiokeoghene" },
  { email: "ciscojoshua397@gmail.com", username: "ciscojoshua397", display_name: "Cisco Joshua" },
  { email: "eniolataiwo479@gmail.com", username: "eniolataiwo479", display_name: "Eniola Taiwo" },
  { email: "derryscott18@gmail.com", username: "derryscott18", display_name: "Derry Official" },
  { email: "sickledemon1@gmail.com", username: "sickledemon1", display_name: "Sickledemon" },
  { email: "exoduscaleb18@gmail.com", username: "exoduscaleb18", display_name: "Caleb Exodus" },
  { email: "evacharity704@gmail.com", username: "evacharity704", display_name: "Evacharity" },
  { email: "obideword2020@gmail.com", username: "obideword2020", display_name: "Obideword" },
  { email: "goodystan5@gmail.com", username: "goodystan5", display_name: "Goodystan" },
  { email: "izuchukwuekeneeze20@gmail.com", username: "izuchukwuekeneeze20", display_name: "Izuchukwuekeneeze" },
  { email: "okeogheneissachar@gmail.com", username: "okeogheneissachar", display_name: "Okeogheneissachar" },
  { email: "chikwenducalebify@gmail.com", username: "chikwenducalebify", display_name: "Chikwenducalebify" },
  { email: "chrisrosebud259@gmal.com", username: "chrisrosebud259", display_name: "Chris Rosebud" },
  { email: "gabbieriel012@gmail.com", username: "gabbieriel012", display_name: "Gabbieriel" },
  { email: "loverboyog83@gmail.com", username: "loverboyog83", display_name: "Loverboyog" },
  { email: "abdulrahmonayinla76@gmail.com", username: "abdulrahmonayinla76", display_name: "Abdulrahmonayinla" },
  { email: "fortwayne2006@gmail.com", username: "fortwayne2006", display_name: "Fortwayne" },
  { email: "tonyk6382@gmail.com", username: "tonyk6382", display_name: "TERLUMUN KENNETH" },
  { email: "abonemmanuel1@gmail.com", username: "abonemmanuel1", display_name: "Abonemmanuel" },
  { email: "ellab8713@gmail.com", username: "ellab8713", display_name: "Ellab" },
  { email: "samteemy144@gmail.com", username: "samteemy144", display_name: "Awotedu Oladipupo" },
  { email: "fahozandaudadelakun01@gmail.com", username: "fahozandaudadelakun01", display_name: "Fahozan Adelakun" },
  { email: "ikogeephraim1@gmail.com", username: "ikogeephraim1", display_name: "Ikogeephraim" },
  { email: "chibuezeog32@gmail.com", username: "chibuezeog32", display_name: "Chibuezeog" },
  { email: "divinegiftamarachukwu@gmail.com", username: "divinegiftamarachukwu", display_name: "Divinegiftamarachukwu" },
  { email: "davincent078@gmail.com", username: "davincent078", display_name: "David Vincent" },
  { email: "arikearike666@gmail.com", username: "arikearike666", display_name: "Arikearike" },
  { email: "davidelue57@gmail.com", username: "davidelue57", display_name: "Davidelue" },
  { email: "bluestorm9821@gmail.com", username: "bluestorm9821", display_name: "Bluestorm" },
  { email: "luckychidera51@gmail.com", username: "luckychidera51", display_name: "Luckychidera" },
  { email: "ee6016405@gmail.com", username: "ee6016405", display_name: "Ee" },
  { email: "henrycoder20@gmail.com", username: "henrycoder20", display_name: "Henrycoder" },
  { email: "israelikani954@gmail.com", username: "israelikani954", display_name: "Isreal David" },
  { email: "malikkadir5566@gmail.com", username: "malikkadir5566", display_name: "Malikkadir" },
  { email: "oluwakayodeoluwatobiloba1@gmail.com", username: "oluwakayodeoluwatobiloba1", display_name: "Oluwakayodeoluwatobiloba" },
  { email: "odunright19@gmail.com", username: "odunright19", display_name: "Odunright" },
  { email: "fchibueze444@gmail.com", username: "fchibueze444", display_name: "Fchibueze" },
  { email: "tochexgaming1@gmail.com", username: "tochexgaming1", display_name: "Tochex Games" },
  { email: "tiflexmicheal@gmail.com", username: "tiflexmicheal", display_name: "Tiflexmicheal" },
  { email: "kksmk08@gmail.com", username: "kksmk08", display_name: "Kksmk" },
  { email: "pleaseofa@gmail.com", username: "pleaseofa", display_name: "Pleaseofa" },
  { email: "controller164@gmail.com", username: "controller164", display_name: "Controller" },
  { email: "tomiwaoguntola40@gmail.com", username: "tomiwaoguntola40", display_name: "Tomiwa Oguntola" },
  { email: "abonemmanuel@gmail.com", username: "abonemmanuel", display_name: "Abonemmanuel" },
  { email: "bace9894@gmail.com", username: "bace9894", display_name: "VICTOR ADETILOYE" },
  { email: "whitejoshua2005@gmail.com", username: "whitejoshua2005", display_name: "Whitejoshua" },
  { email: "milliyoung231@gmail.com", username: "milliyoung231", display_name: "Milliyoung" },
  { email: "tobiabioduncharles@gmail.com", username: "tobiabioduncharles", display_name: "Tobiabioduncharles" },
  { email: "luisdrunk358@gmail.com", username: "luisdrunk358", display_name: "Divine Favour" },
  { email: "kingtka361@gmail.com", username: "kingtka361", display_name: "Kingtka" },
  { email: "sadikgwandu73@gmail.com", username: "sadikgwandu73", display_name: "Sadikgwandu" },
  { email: "babsabayomi84@gmail.com", username: "babsabayomi84", display_name: "Ghost Gang" },
  { email: "babatundeemmanuel8599@gmail.com", username: "babatundeemmanuel85991", display_name: "Babatundeemmanuel" },
  { email: "akintundeopeyemi001@gmail.com", username: "akintundeopeyemi001", display_name: "Akintunde Opeyemi" },
  { email: "saniyoprecious8@gmail.com", username: "saniyoprecious8", display_name: "Saniyoprecious" },
  { email: "ainabosetaiwo@gmail.com", username: "ainabosetaiwo", display_name: "Ayinde Usman" },
  { email: "nwadishimichael488@gmail.com", username: "nwadishimichael488", display_name: "Nwadishimichael" },
  { email: "akanniemma@gmail.com", username: "akanniemma", display_name: "Emmanuel Akanni" },
  { email: "osukamichael514@gmail.com", username: "osukamichael514", display_name: "Osukamichael" },
  { email: "babatundeemmanuel@gmail.com", username: "babatundeemmanuel", display_name: "Babatundeemmanuel" },
  { email: "chinedunwoke366@gmail.com", username: "chinedunwoke366", display_name: "Chinedunwoke" },
  { email: "fffboy321@gmail.com", username: "fffboy321", display_name: "Fffboy" },
  { email: "arinzedavid374@gmail.com", username: "arinzedavid374", display_name: "Arinzedavid" },
  { email: "enyeobidivinegift@gmail.com", username: "enyeobidivinegift", display_name: "Enyeobidivinegift" },
  { email: "volarmec@gmail.com", username: "volarmec", display_name: "Volarmec" },
  { email: "davidmassaquoi30@gmail.com", username: "davidmassaquoi30", display_name: "Davidmassaquoi" },
  { email: "q4716831@gmail.com", username: "q4716831", display_name: "Q" },
  { email: "raph207zack@gmail.com", username: "raph207zack", display_name: "Raphael Zack" },
  { email: "efegodswill10@gmail.com", username: "efegodswill10", display_name: "Efe Godswill" },
  { email: "odibomaghan@gmail.com", username: "odibomaghan", display_name: "Odibomaghan" },
  { email: "ninaokoroafor@gmail.com", username: "ninaokoroafor", display_name: "Nina Okoroafor" },
  { email: "nathanboadu366@gmail.com", username: "nathanboadu366", display_name: "Nathan Boadu" },
  { email: "xtreme.gamerj1@gmail.com", username: "xtremegamerj1", display_name: "JOSEPH GABRIEL" },
  { email: "dvibe1468@gmail.com", username: "dvibe1468", display_name: "Abdulfatai Ibrahim" },
  { email: "osagieirabor798@gmail.com", username: "osagieirabor798", display_name: "Irabor" },
  { email: "akinloyebasit40@gmail.com", username: "akinloyebasit40", display_name: "Akinloye Basit" },
  { email: "paoyeanleng@gmail.com", username: "paoyeanleng", display_name: "PAV YEAN Leng" },
  { email: "olaigbeanjola96@gmail.com", username: "olaigbeanjola96", display_name: "Anjola Olaigbe" },
  { email: "joyceroberts111@gmail.com", username: "joyceroberts111", display_name: "Emmanuel Roberts" },
  { email: "abdulrahmansalaudeen007@gmail.com", username: "abdulrahmansalaudeen007", display_name: "Abdulrahmansalaudeen" },
  { email: "nnannagodhand@gmail.com", username: "nnannagodhand", display_name: "nnanna God hand" },
  { email: "omalejoe0@gmail.com", username: "omalejoe0", display_name: "Great Joseph" },
  { email: "smartd833@gmail.com", username: "smartd833", display_name: "Smartd" },
  { email: "fifoluwaadams@gmail.com", username: "fifoluwaadams", display_name: "Fifoluwa Sule-adams" },
  { email: "michaelogbonna365@gmail.com", username: "michaelogbonna365", display_name: "michaelogbonna365" },
  { email: "bennyabah321@gmail.com", username: "bennyabah321", display_name: "Bennyabah" },
  { email: "megawolves233@gmail.com", username: "megawolves233", display_name: "Megawolves" },
  { email: "gloryfrank530@gmail.com", username: "gloryfrank530", display_name: "Glory Frank" },
  { email: "tinaamuga55@gmail.com", username: "tinaamuga55", display_name: "Promise Benjamin" },
  { email: "victorchisomezezuma@gmail.com", username: "victorchisomezezuma", display_name: "Victor Chisom" },
];

async function importUsers() {
  let created = 0, skipped = 0, failed = 0;
  console.log(`Starting import of ${users.length} users...\n`);

  for (let i = 0; i < users.length; i++) {
    const u = users[i];
    process.stdout.write(`[${i+1}/${users.length}] ${u.email} ... `);

    try {
      // Create auth user with admin API — no password set,
      // email is confirmed so they only need Forgot Password to get in
      const { data, error } = await supabase.auth.admin.createUser({
        email: u.email,
        email_confirm: true,  // confirmed — they were real members
        user_metadata: {
          username: u.username,
          display_name: u.display_name,
        },
      });

      if (error) {
        if (error.message.includes('already been registered') || error.message.includes('already exists')) {
          console.log('SKIPPED (exists)');
          skipped++;
        } else {
          console.log(`FAILED: ${error.message}`);
          failed++;
        }
        continue;
      }

      const uid = data.user.id;

      // Upsert profile row with display name and username
      const { error: profileError } = await supabase
        .from('profiles')
        .upsert({
          id: uid,
          username: u.username,
          display_name: u.display_name,
          role: 'user',
          verification_status: 'unverified',
        }, { onConflict: 'id' });

      if (profileError) {
        console.log(`CREATED (profile error: ${profileError.message})`);
      } else {
        console.log('OK');
      }
      created++;

    } catch (err) {
      console.log(`ERROR: ${err.message}`);
      failed++;
    }

    // Small delay to avoid rate limiting
    if (i % 50 === 49) {
      console.log('\nPausing 2s to avoid rate limits...\n');
      await new Promise(r => setTimeout(r, 2000));
    }
  }

  console.log(`\n============================================`);
  console.log(`Import complete!`);
  console.log(`  Created:  ${created}`);
  console.log(`  Skipped:  ${skipped} (already existed)`);
  console.log(`  Failed:   ${failed}`);
  console.log(`============================================`);
  console.log(`\nAll ${created} users need to use Forgot Password to log in.`);
}

importUsers().catch(console.error);