import 'package:flutter/material.dart';
import 'how_to_model.dart';

const Map<String, GameHowTo> howToArenaA = <String, GameHowTo>{
  '2048': GameHowTo(
    name: '2048',
    icon: Icons.numbers_rounded,
    color: Color(0xFFEDC22E),
    goal: 'Slide tiles and join matching numbers to build bigger ones.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Join the numbers', text: 'Two tiles with the same number join into one bigger tile. Keep joining to score points.', demo: DemoKind.watch, actor: Icons.numbers_rounded, target: Icons.merge_rounded),
      TutorialStep(title: 'Swipe to slide', text: 'Swipe up, down, left or right. Every tile slides as far as it can in that direction.', demo: DemoKind.swipe, actor: Icons.grid_view_rounded, target: Icons.arrow_forward_rounded, dx: 1, dy: 0),
      TutorialStep(title: 'Plan your swipes', text: 'A new tile appears after each swipe. The game ends when the board is full and nothing can join.', demo: DemoKind.watch, actor: Icons.grid_on_rounded, target: Icons.block_rounded),
      TutorialStep(title: 'Keep big tiles close', text: 'Park your biggest tile in one corner and build next to it. Try not to swipe in too many directions.', demo: DemoKind.swipe, actor: Icons.star_rounded, target: Icons.trending_up_rounded, dx: -1, dy: 0),
    ],
  ),
  'airhockey': GameHowTo(
    name: 'Air Hockey',
    icon: Icons.sports_hockey_rounded,
    color: Color(0xFF29B6F6),
    goal: "Hit the puck into Ryan's goal. First to 7 goals wins.",
    steps: <TutorialStep>[
      TutorialStep(title: 'Score goals', text: "Knock the puck into the gap in Ryan's goal at the top. Each goal is one point.", demo: DemoKind.watch, actor: Icons.sports_hockey_rounded, target: Icons.sports_esports_rounded),
      TutorialStep(title: 'Drag your mallet', text: 'Slide your finger on the bottom half of the table. Your mallet follows just above your finger.', demo: DemoKind.drag, actor: Icons.sports_hockey_rounded, target: Icons.album_rounded, dx: 1, dy: -0.5),
      TutorialStep(title: 'Guard your goal', text: 'The gap at the bottom is your goal. Keep your mallet between the puck and the gap.', demo: DemoKind.watch, actor: Icons.shield_rounded, target: Icons.album_rounded),
      TutorialStep(title: 'First to 7', text: 'The first side to 7 goals wins. When the 3 minute clock ends, whoever is ahead wins.', demo: DemoKind.watch, actor: Icons.timer_rounded, target: Icons.emoji_events_rounded),
      TutorialStep(title: 'Swing fast', text: 'A faster swing sends the puck faster. Bounce it off the walls to surprise Ryan.', demo: DemoKind.swipe, actor: Icons.sports_hockey_rounded, target: Icons.bolt_rounded, dx: 0, dy: -1),
    ],
  ),
  'astracolony': GameHowTo(
    name: 'Astra Colony',
    icon: Icons.satellite_alt_rounded,
    color: Color(0xFF3DD6FF),
    goal: 'Collect power cells and deposit exactly 15 units at the reactor.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Power the reactor', text: 'The Solar Array needs exactly 15 units. Collect power cells that add up to that number.', demo: DemoKind.watch, actor: Icons.bolt_rounded, target: Icons.wb_sunny_rounded),
      TutorialStep(title: 'Walk with the stick', text: 'Drag the joystick at the bottom left to walk. Walk over a power cell to pick it up.', demo: DemoKind.drag, actor: Icons.person_rounded, target: Icons.bolt_rounded, dx: 1, dy: 0),
      TutorialStep(title: 'Tap deposit', text: 'Stand close to the Solar Array and tap the DEPOSIT button to add your cells to the total.', demo: DemoKind.tap, actor: Icons.person_rounded, target: Icons.savings_rounded),
      TutorialStep(title: 'Do not go over', text: 'If the total goes past 15, the console overloads and your cells reset. Add up your numbers first.', demo: DemoKind.watch, actor: Icons.calculate_rounded, target: Icons.warning_amber_rounded),
    ],
  ),
  'ayo': GameHowTo(
    name: 'Ayo',
    icon: Icons.circle,
    color: Color(0xFF8D6E63),
    goal: 'Capture 25 seeds before Ryan does.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Capture 25 seeds', text: 'Win seeds from Ryan by planning where your last seed lands. The first to 25 wins.', demo: DemoKind.watch, actor: Icons.grain_rounded, target: Icons.emoji_events_rounded),
      TutorialStep(title: 'Pick a pit', text: 'Tap one of your six pits on the bottom row. All its seeds are picked up.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.circle_outlined),
      TutorialStep(title: 'Sow the seeds', text: 'The seeds drop one by one into the next pits, going counter-clockwise around the board.', demo: DemoKind.move, actor: Icons.grain_rounded, target: Icons.circle_outlined),
      TutorialStep(title: 'Make a capture', text: 'If your last seed lands in one of Ryan\'s pits and makes it 2 or 3 seeds, you take them. Pits just before it with 2 or 3 are taken too.', demo: DemoKind.watch, actor: Icons.grain_rounded, target: Icons.savings_rounded),
      TutorialStep(title: 'Count ahead', text: 'Before you tap, count where your last seed will land. Aim for a pit of Ryan\'s that has 1 or 2 seeds.', demo: DemoKind.watch, actor: Icons.lightbulb_rounded, target: Icons.my_location_rounded),
    ],
  ),
  'basketball': GameHowTo(
    name: 'Basketball',
    icon: Icons.sports_basketball_rounded,
    color: Color(0xFFFF7043),
    goal: 'Score as many baskets as you can in 60 seconds.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Beat the clock', text: 'You have 60 seconds. Each basket is worth 2 points.', demo: DemoKind.watch, actor: Icons.sports_basketball_rounded, target: Icons.timer_rounded),
      TutorialStep(title: 'Pull back and let go', text: 'Drag backward anywhere on the screen like a sling, then lift your finger to shoot. A longer pull throws harder.', demo: DemoKind.drag, actor: Icons.sports_basketball_rounded, target: Icons.gps_fixed_rounded, dx: 0.4, dy: -1),
      TutorialStep(title: 'Follow the dots', text: 'The dotted line shows the start of the ball path. You judge the rest of the arc yourself.', demo: DemoKind.watch, actor: Icons.timeline_rounded, target: Icons.sports_basketball_rounded),
      TutorialStep(title: 'Build a streak', text: 'Scoring 3 or 5 in a row makes each basket worth more. A miss ends the streak.', demo: DemoKind.watch, actor: Icons.local_fire_department_rounded, target: Icons.trending_up_rounded),
      TutorialStep(title: 'Watch the hoop', text: 'The hoop moves after every second basket, so change your aim. A bounce off the backboard can still go in.', demo: DemoKind.watch, actor: Icons.sports_basketball_rounded, target: Icons.swap_horiz_rounded),
    ],
  ),
  'battleship': GameHowTo(
    name: 'Battleship',
    icon: Icons.directions_boat_rounded,
    color: Color(0xFF1E88E5),
    goal: "Sink all 5 of Ryan's ships before he sinks yours.",
    steps: <TutorialStep>[
      TutorialStep(title: 'Sink the fleet', text: "Each side hides 5 ships. Find and sink all of Ryan's ships first to win.", demo: DemoKind.watch, actor: Icons.directions_boat_rounded, target: Icons.emoji_events_rounded),
      TutorialStep(title: 'Place your ships', text: 'Tap a ship, then tap the grid to place it. Use ROTATE to turn it, or RANDOM to place all five for you.', demo: DemoKind.move, actor: Icons.directions_boat_rounded, target: Icons.grid_on_rounded),
      TutorialStep(title: 'Fire at Ryan', text: "You and Ryan take turns. Tap a square on Ryan's waters to fire.", demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.gps_fixed_rounded),
      TutorialStep(title: 'Hits and misses', text: 'Red means you hit a ship. A white dot means a miss. Hit every square of a ship to sink it.', demo: DemoKind.watch, actor: Icons.whatshot_rounded, target: Icons.directions_boat_rounded),
      TutorialStep(title: 'Hunt near hits', text: 'After a hit, fire at the squares right next to it. The rest of that ship is close by.', demo: DemoKind.tap, actor: Icons.lightbulb_rounded, target: Icons.my_location_rounded),
    ],
  ),
  'blackjack': GameHowTo(
    name: 'Blackjack',
    icon: Icons.style_rounded,
    color: Color(0xFF2E7D32),
    goal: "Get closer to 21 than Ryan's hand without going over.",
    steps: <TutorialStep>[
      TutorialStep(title: 'Reach 21', text: 'Get a hand total closer to 21 than Ryan, but never go over 21. Number cards count as their number and J, Q, K count as 10.', demo: DemoKind.watch, actor: Icons.style_rounded, target: Icons.emoji_events_rounded),
      TutorialStep(title: 'Deal and hit', text: 'Tap DEAL to start. Tap HIT to take another card.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.add_circle_rounded),
      TutorialStep(title: 'Stand when ready', text: 'Tap STAND to keep your cards. Then Ryan reveals his hand and keeps drawing until he has 17 or more.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.back_hand_rounded),
      TutorialStep(title: 'Do not bust', text: 'Go over 21 and you bust and lose right away. An Ace counts as 11, or as 1 if 11 would be too much.', demo: DemoKind.watch, actor: Icons.warning_amber_rounded, target: Icons.style_rounded),
      TutorialStep(title: 'Know when to stop', text: 'With 17 or more it is risky to hit. With 11 or less you can always hit safely.', demo: DemoKind.watch, actor: Icons.lightbulb_rounded, target: Icons.check_circle_rounded),
    ],
  ),
  'blockdrop': GameHowTo(
    name: 'Block Drop',
    icon: Icons.view_module_rounded,
    color: Color(0xFF7E57C2),
    goal: 'Fill whole rows with falling pieces so they clear.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Clear rows', text: 'Pieces fall from the top. Fill a whole row with no gaps and it disappears. Clearing 4 rows at once scores the most.', demo: DemoKind.watch, actor: Icons.view_module_rounded, target: Icons.check_rounded),
      TutorialStep(title: 'Drag to move', text: 'Drag on the board to slide the falling piece left or right. You can also use the buttons.', demo: DemoKind.drag, actor: Icons.view_module_rounded, target: Icons.vertical_align_bottom_rounded, dx: 1, dy: 0),
      TutorialStep(title: 'Tap to turn', text: 'Tap the board to rotate the piece so it fits the gap.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.rotate_right_rounded),
      TutorialStep(title: 'Use the keyboard', text: 'Left and right move the piece, down drops it faster, up turns it. Space drops it all the way.', demo: DemoKind.keys, actor: Icons.view_module_rounded, target: Icons.vertical_align_bottom_rounded, keys: <String>['UP', 'LEFT', 'DOWN', 'RIGHT'], pcOnly: true),
      TutorialStep(title: 'Hold a piece', text: 'HOLD saves the falling piece for later and swaps in the saved one. You can hold once per piece.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.save_alt_rounded),
      TutorialStep(title: 'Do not stack high', text: 'Pieces fall faster as your level goes up. The game ends when the stack reaches the top, so keep it low and flat.', demo: DemoKind.watch, actor: Icons.speed_rounded, target: Icons.warning_amber_rounded),
    ],
  ),
  'bubbleshooter': GameHowTo(
    name: 'Bubble Shooter',
    icon: Icons.bubble_chart_rounded,
    color: Color(0xFFEC407A),
    goal: 'Pop all the bubbles by matching 3 or more of the same colour.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Pop the bubbles', text: 'Shoot bubbles to join 3 or more of the same colour. Clear the board to reach the next level.', demo: DemoKind.watch, actor: Icons.bubble_chart_rounded, target: Icons.auto_awesome_rounded),
      TutorialStep(title: 'Aim and shoot', text: 'Drag on the board to aim. The dotted line shows where your bubble will go, and it bounces off the walls. Let go to fire.', demo: DemoKind.drag, actor: Icons.gps_fixed_rounded, target: Icons.bubble_chart_rounded, dx: 0.6, dy: -1),
      TutorialStep(title: 'Swap bubbles', text: 'Tap the small bubble next to the launcher to swap it with the one that is loaded.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.swap_horiz_rounded),
      TutorialStep(title: 'Drop bonus', text: 'Bubbles left hanging with nothing above them fall down too. That earns bonus points.', demo: DemoKind.watch, actor: Icons.arrow_downward_rounded, target: Icons.stars_rounded),
      TutorialStep(title: 'Watch the red line', text: 'If you keep missing, a new row drops from the top. If bubbles cross the red line, the game ends. Aim for matches on every shot.', demo: DemoKind.watch, actor: Icons.warning_amber_rounded, target: Icons.flag_rounded),
    ],
  ),
  'checkers': GameHowTo(
    name: 'Checkers',
    icon: Icons.grid_view_rounded,
    color: Color(0xFFE64A19),
    goal: "Capture all of Ryan's pieces or leave him with no moves.",
    steps: <TutorialStep>[
      TutorialStep(title: 'Beat Ryan', text: "Capture every one of Ryan's pieces, or block them so Ryan has no move left.", demo: DemoKind.watch, actor: Icons.grid_view_rounded, target: Icons.emoji_events_rounded),
      TutorialStep(title: 'Move a piece', text: 'Tap one of your orange pieces, then tap a highlighted square. Pieces move diagonally forward.', demo: DemoKind.move, actor: Icons.circle, target: Icons.check_circle_rounded),
      TutorialStep(title: 'Jump to capture', text: 'Jump over one of Ryan\'s pieces to take it. If you can jump, you must jump, and you can keep jumping in a chain.', demo: DemoKind.move, actor: Icons.circle, target: Icons.flash_on_rounded),
      TutorialStep(title: 'Make a king', text: 'Reach the far row to crown a piece. A king can move and capture backwards too.', demo: DemoKind.watch, actor: Icons.circle, target: Icons.workspace_premium_rounded),
      TutorialStep(title: 'Stay together', text: 'Keep your pieces in groups so Ryan cannot jump them easily. Keep a few at the back to stop his kings.', demo: DemoKind.watch, actor: Icons.shield_rounded, target: Icons.groups_rounded),
    ],
  ),
  'chess': GameHowTo(
    name: 'Chess',
    icon: Icons.castle_rounded,
    color: Color(0xFF5D4037),
    goal: "Trap Ryan's king so it cannot escape (checkmate).",
    steps: <TutorialStep>[
      TutorialStep(title: 'Checkmate Ryan', text: "Attack Ryan's king so that it has no safe square. That is checkmate and you win.", demo: DemoKind.watch, actor: Icons.castle_rounded, target: Icons.emoji_events_rounded),
      TutorialStep(title: 'Move a piece', text: 'Tap one of your pieces, then tap the square where you want it to go.', demo: DemoKind.move, actor: Icons.castle_rounded, target: Icons.check_circle_rounded),
      TutorialStep(title: 'Normal chess rules', text: 'Castling, en passant and promotion all work like real chess. Each piece moves in its own way.', demo: DemoKind.watch, actor: Icons.extension_rounded, target: Icons.menu_book_rounded),
      TutorialStep(title: 'Learn mode', text: 'Tap the learn button at the top to have Ryan explain your moves. Turn it off to play Ryan at full strength.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.lightbulb_rounded),
      TutorialStep(title: 'Protect your king', text: 'Before each move, check what Ryan can attack. Take care of your king and your queen first.', demo: DemoKind.watch, actor: Icons.shield_rounded, target: Icons.visibility_rounded),
    ],
  ),
  'chronospire': GameHowTo(
    name: 'Chrono Spire',
    icon: Icons.science_rounded,
    color: Color(0xFF34D399),
    goal: 'Shoot the bio-beasts and survive as many waves as you can.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Survive the waves', text: 'Beat each wave of bio-beasts. The game ends when they overwhelm you. Your score grows as you win.', demo: DemoKind.watch, actor: Icons.science_rounded, target: Icons.emoji_events_rounded),
      TutorialStep(title: 'Left stick moves', text: 'Drag the left stick to move your drone around the arena.', demo: DemoKind.drag, actor: Icons.control_camera_rounded, target: Icons.my_location_rounded, dx: -1, dy: 0),
      TutorialStep(title: 'Right stick shoots', text: 'Drag the right stick to aim and fire. Nothing shoots until you push it.', demo: DemoKind.drag, actor: Icons.gps_fixed_rounded, target: Icons.bug_report_outlined, dx: 1, dy: -0.4),
      TutorialStep(title: 'Switch payloads', text: 'Tap the payload button to swap between Acid, Thermal and Electro. Hit with Acid and then Thermal quickly for a bonus explosion.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.science_rounded),
      TutorialStep(title: 'Dodge and aim well', text: 'Tap Dodge for a quick burst of speed and a moment of safety. Shoot the glowing weak point on each enemy: gold slows it, blue stops its attack.', demo: DemoKind.tap, actor: Icons.directions_run_rounded, target: Icons.shield_rounded),
    ],
  ),
  'colonybuilder': GameHowTo(
    name: 'Colony Builder',
    icon: Icons.holiday_village_rounded,
    color: Color(0xFFFFB300),
    goal: 'Earn enough total energy before time runs out.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Earn the energy', text: 'Reach the energy target before the timer ends. Buildings keep earning energy every second.', demo: DemoKind.watch, actor: Icons.bolt_rounded, target: Icons.timer_rounded),
      TutorialStep(title: 'Tap to build', text: 'Tap an empty slot to see the buildings you can buy. Tap one you can afford to start building it.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.add_box_rounded),
      TutorialStep(title: 'Cost and payback', text: 'Cheap buildings pay for themselves fast but earn less. Expensive ones earn more each second.', demo: DemoKind.watch, actor: Icons.paid_rounded, target: Icons.trending_up_rounded),
      TutorialStep(title: 'Build early', text: 'You start with 25 energy, enough for a Solar Array. Build right away, since every second a building runs earns you more.', demo: DemoKind.watch, actor: Icons.holiday_village_rounded, target: Icons.speed_rounded),
    ],
  ),
  'colorclash': GameHowTo(
    name: 'Color Clash',
    icon: Icons.palette_rounded,
    color: Color(0xFFE53935),
    goal: 'Be the first to play all the cards in your hand.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Empty your hand', text: 'Be the first player with no cards left. Then you score the points left in the other hands.', demo: DemoKind.watch, actor: Icons.style_rounded, target: Icons.emoji_events_rounded),
      TutorialStep(title: 'Match the top card', text: 'Tap a bright card that matches the colour or the number or symbol of the top card on the pile.', demo: DemoKind.move, actor: Icons.style_rounded, target: Icons.layers_rounded),
      TutorialStep(title: 'Action cards', text: 'Skip jumps the next player. Reverse flips the direction. A +2 card makes the next player draw two cards.', demo: DemoKind.watch, actor: Icons.bolt_rounded, target: Icons.person_off_rounded),
      TutorialStep(title: 'Wild cards', text: 'A Wild lets you choose the colour. Wild +4 also makes the next player draw four, but you can only play it if you have no card of the current colour.', demo: DemoKind.watch, actor: Icons.palette_rounded, target: Icons.auto_awesome_rounded),
      TutorialStep(title: 'Stuck? Draw', text: 'If you cannot play, draw a card. Your last card is called automatically, so just play it.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.add_circle_outline_rounded),
    ],
  ),
  'connect4': GameHowTo(
    name: 'Connect Four',
    icon: Icons.apps_rounded,
    color: Color(0xFF1976D2),
    goal: 'Line up 4 of your pieces in a row before Ryan does.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Get four in a row', text: 'Make a line of 4 of your pieces. It can go across, up and down, or on a slant.', demo: DemoKind.watch, actor: Icons.circle, target: Icons.emoji_events_rounded),
      TutorialStep(title: 'Tap a column', text: 'Tap a column to drop your piece in. It falls to the lowest empty spot.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.arrow_downward_rounded),
      TutorialStep(title: 'Take turns with Ryan', text: 'You drop one piece, then Ryan drops one. Watch his pieces too.', demo: DemoKind.watch, actor: Icons.person_rounded, target: Icons.smart_toy_rounded),
      TutorialStep(title: 'Block and build', text: 'If Ryan has 3 in a row, block the end right away. Try to make two lines of 3 at once so he cannot block both.', demo: DemoKind.watch, actor: Icons.block_rounded, target: Icons.apps_rounded),
    ],
  ),
  'darts': GameHowTo(
    name: 'Darts',
    icon: Icons.my_location_rounded,
    color: Color(0xFFD32F2F),
    goal: 'Score more points than Ryan over 5 rounds.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Beat Ryan', text: 'Each round you throw 3 darts, then Ryan throws 3. After 5 rounds the higher total wins.', demo: DemoKind.watch, actor: Icons.my_location_rounded, target: Icons.emoji_events_rounded),
      TutorialStep(title: 'Press, aim, release', text: 'Press on the board and slide your finger to move the aim point. It sits above your finger. Let go to throw.', demo: DemoKind.drag, actor: Icons.gps_fixed_rounded, target: Icons.my_location_rounded, dx: 0.5, dy: -0.5),
      TutorialStep(title: 'Be quick', text: 'The circle around your aim shows how wobbly your throw will be. It grows the longer you hold, so aim fast.', demo: DemoKind.watch, actor: Icons.timelapse_rounded, target: Icons.adjust_rounded),
      TutorialStep(title: 'Know the board', text: 'The bullseye is 50 and the outer bull is 25. The thin outer ring doubles the number and the inner ring triples it.', demo: DemoKind.watch, actor: Icons.stars_rounded, target: Icons.my_location_rounded),
      TutorialStep(title: 'Go for triple 20', text: 'The triple 20 is worth 60 points. Aim there if you can, or just stay near the middle.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.my_location_rounded),
    ],
  ),
  'dashrunner': GameHowTo(
    name: 'Dash Runner',
    icon: Icons.directions_run_rounded,
    color: Color(0xFF00ACC1),
    goal: 'Run as far as you can, jump and slide past obstacles, and grab coins.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Keep running', text: 'Your runner never stops. Go as far as you can. Distance scores points, and one hit ends the run.', demo: DemoKind.watch, actor: Icons.directions_run_rounded, target: Icons.flag_rounded),
      TutorialStep(title: 'Tap to jump', text: 'Tap the screen or the JUMP button to jump over crates.', demo: DemoKind.tap, actor: Icons.directions_run_rounded, target: Icons.arrow_upward_rounded),
      TutorialStep(title: 'Swipe down to slide', text: 'Swipe down or tap SLIDE to duck under the high bars.', demo: DemoKind.swipe, actor: Icons.directions_run_rounded, target: Icons.arrow_downward_rounded, dx: 0, dy: 1),
      TutorialStep(title: 'Use the keyboard', text: 'Press Space or the up arrow to jump. Press the down arrow to slide.', demo: DemoKind.keys, actor: Icons.directions_run_rounded, target: Icons.flag_rounded, keys: <String>['SPACE'], pcOnly: true),
      TutorialStep(title: 'Grab the coins', text: 'Each coin is worth 5 points. Some float high, so jump to reach them. The game gets faster as you go.', demo: DemoKind.tap, actor: Icons.monetization_on_rounded, target: Icons.stars_rounded),
    ],
  ),
};
