import 'package:flutter/material.dart';
import 'how_to_model.dart';

const Map<String, GameHowTo> howToArenaC = <String, GameHowTo>{
  'rummy': GameHowTo(
    name: 'Rummy',
    icon: Icons.style_rounded,
    color: Color(0xFF2E7D32),
    goal: 'Make sets and runs and get rid of all your cards before Ryan does.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Empty your hand', text: 'You and Ryan take turns. Be the first to get rid of every card in your hand to win.', demo: DemoKind.watch, actor: Icons.style_rounded, target: Icons.emoji_events_rounded),
      TutorialStep(title: 'Draw a card', text: 'Start each turn by tapping the face down deck or the top card of the discard pile.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.layers_rounded),
      TutorialStep(title: 'Make a meld', text: 'Tap 3 or more cards that go together, then tap MELD. A set is the same number in different suits. A run is 3 in a row in one suit.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.view_agenda_rounded),
      TutorialStep(title: 'Add to melds', text: 'Pick cards that fit, then tap a meld on the table. It can be yours or Ryan.', demo: DemoKind.move, actor: Icons.add_circle_outline_rounded, target: Icons.view_agenda_rounded),
      TutorialStep(title: 'End with a discard', text: 'Pick one card and tap DISCARD to finish your turn. Meld early so you are not stuck holding points.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.delete_rounded),
    ],
  ),
  'signalmatch': GameHowTo(
    name: 'Signal Match',
    icon: Icons.diamond_rounded,
    color: Color(0xFFFFC85C),
    goal: 'Slice the gem with the right answer and skip the wrong ones.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Find the answer', text: 'A question shows up and gems with answers fly up. Slice the one with the right answer.', demo: DemoKind.watch, actor: Icons.diamond_rounded, target: Icons.quiz_rounded),
      TutorialStep(title: 'Swipe through it', text: 'Slide your finger through the correct gem. You do not tap, you swipe across it.', demo: DemoKind.swipe, actor: Icons.diamond_rounded, target: Icons.gesture_rounded, dx: 1, dy: -0.5),
      TutorialStep(title: 'Watch your hearts', text: 'You have 3 hearts. Slicing a wrong gem, or letting the right one fall, costs a heart.', demo: DemoKind.watch, actor: Icons.favorite_rounded, target: Icons.heart_broken_rounded),
      TutorialStep(title: 'Read first', text: 'Every right slice gives 20 points. Read the question before you swipe so you do not slice a wrong gem.', demo: DemoKind.watch, actor: Icons.visibility_rounded, target: Icons.stars_rounded),
    ],
  ),
  'simon': GameHowTo(
    name: 'Simon Says',
    icon: Icons.palette_rounded,
    color: Color(0xFFE53935),
    goal: 'Remember the colour pattern and tap it back in the same order.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Watch the lights', text: 'Four coloured squares light up one by one. Watch them closely and remember the order.', demo: DemoKind.watch, actor: Icons.visibility_rounded, target: Icons.palette_rounded),
      TutorialStep(title: 'Tap it back', text: 'When it says your turn, tap the squares in the same order you saw.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.palette_rounded),
      TutorialStep(title: 'It gets longer', text: 'Each round adds one more colour to the pattern. One wrong tap ends the game.', demo: DemoKind.watch, actor: Icons.trending_up_rounded, target: Icons.block_rounded),
      TutorialStep(title: 'Say it in your head', text: 'Say the colours in your head as they flash. Longer rounds give you more points.', demo: DemoKind.watch, actor: Icons.psychology_rounded, target: Icons.stars_rounded),
    ],
  ),
  'skyhopper': GameHowTo(
    name: 'Sky Hopper',
    icon: Icons.flutter_dash_rounded,
    color: Color(0xFF29B6F6),
    goal: 'Fly the bird through the gaps in the pipes for as long as you can.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Pass the pipes', text: 'Every pipe you fly past gives you 1 point. Touching a pipe or the ground ends the run.', demo: DemoKind.watch, actor: Icons.flutter_dash_rounded, target: Icons.arrow_forward_rounded),
      TutorialStep(title: 'Tap to flap', text: 'Tap anywhere on the screen to hop up. The bird falls down between taps.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.flutter_dash_rounded),
      TutorialStep(title: 'Use the keyboard', text: 'On a computer you can press the space bar to flap.', demo: DemoKind.keys, actor: Icons.flutter_dash_rounded, target: Icons.arrow_upward_rounded, keys: <String>['SPACE'], pcOnly: true),
      TutorialStep(title: 'It gets tighter', text: 'The gaps shrink and the pipes go faster as your score grows. Use small, steady taps instead of big ones.', demo: DemoKind.watch, actor: Icons.trending_up_rounded, target: Icons.stars_rounded),
    ],
  ),
  'snake': GameHowTo(
    name: 'Snake',
    icon: Icons.restaurant_rounded,
    color: Color(0xFF43A047),
    goal: 'Eat food to grow your snake without hitting a wall or yourself.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Eat the food', text: 'Your snake keeps moving by itself. Steer it into the food to score 10 points and grow longer.', demo: DemoKind.watch, actor: Icons.pets_rounded, target: Icons.restaurant_rounded),
      TutorialStep(title: 'Tap the arrows', text: 'Use the four arrow buttons under the board to turn up, down, left or right.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.arrow_upward_rounded),
      TutorialStep(title: 'Do not crash', text: 'Hitting a wall or your own body ends the game. You cannot turn straight back on yourself.', demo: DemoKind.watch, actor: Icons.pets_rounded, target: Icons.dangerous_rounded),
      TutorialStep(title: 'Plan ahead', text: 'The longer you get, the less room you have. Turn early and keep space around you.', demo: DemoKind.watch, actor: Icons.lightbulb_rounded, target: Icons.stars_rounded),
    ],
  ),
  'solitaire': GameHowTo(
    name: 'Solitaire',
    icon: Icons.style_rounded,
    color: Color(0xFF0B3D2A),
    goal: 'Move all the cards into four piles, one for each suit, from Ace up to King.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Fill the four piles', text: 'Build each suit from Ace to King in the four piles at the top right. Fill them all to win.', demo: DemoKind.watch, actor: Icons.style_rounded, target: Icons.emoji_events_rounded),
      TutorialStep(title: 'Tap, then tap', text: 'Tap a card, then tap the place you want it to go. Tap the same card again to send it up to its suit pile.', demo: DemoKind.move, actor: Icons.style_rounded, target: Icons.view_agenda_rounded),
      TutorialStep(title: 'Alternate colours', text: 'On the table, put a card on one that is a number higher and the opposite colour. Only a King can go in an empty column.', demo: DemoKind.watch, actor: Icons.swap_vert_rounded, target: Icons.style_rounded),
      TutorialStep(title: 'Use the stock', text: 'Tap the stock to turn over new cards. When it runs out, tap it again to start over.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.layers_rounded),
      TutorialStep(title: 'Undo is free', text: 'Made a mistake? Tap UNDO to take back your last move. Free up face down cards early.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.replay_rounded),
    ],
  ),
  'speedmath': GameHowTo(
    name: 'Speed Math',
    icon: Icons.calculate_rounded,
    color: Color(0xFFFF7043),
    goal: 'Solve as many sums as you can before 30 seconds run out.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Beat the clock', text: 'Tap START and you get 30 seconds. Answer as many sums as you can.', demo: DemoKind.watch, actor: Icons.timer_rounded, target: Icons.calculate_rounded),
      TutorialStep(title: 'Type the answer', text: 'You will see add, take away and times sums. Type the answer, then tap SUBMIT.', demo: DemoKind.tap, actor: Icons.keyboard_rounded, target: Icons.calculate_rounded),
      TutorialStep(title: 'Keep your streak', text: 'Each right answer is worth 10 points plus your streak. A wrong answer resets the streak to zero.', demo: DemoKind.watch, actor: Icons.local_fire_department_rounded, target: Icons.stars_rounded),
      TutorialStep(title: 'Go for speed', text: 'Do not stop on a hard one for too long. A long streak of quick answers scores the most.', demo: DemoKind.watch, actor: Icons.speed_rounded, target: Icons.emoji_events_rounded),
    ],
  ),
  'stacktower': GameHowTo(
    name: 'Stack Tower',
    icon: Icons.layers_rounded,
    color: Color(0xFFAB47BC),
    goal: 'Drop blocks on top of each other to build the tallest tower you can.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Build it high', text: 'A block slides left and right above your tower. Stack as many as you can.', demo: DemoKind.watch, actor: Icons.layers_rounded, target: Icons.trending_up_rounded),
      TutorialStep(title: 'Tap to drop', text: 'Tap anywhere to drop the block. Try to land it right on top of the one below.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.vertical_align_bottom_rounded),
      TutorialStep(title: 'Overhang is cut', text: 'Any part that sticks out gets chopped off, so your tower gets thinner. If a block misses completely, the game ends.', demo: DemoKind.watch, actor: Icons.content_cut_rounded, target: Icons.layers_rounded),
      TutorialStep(title: 'Go for perfect', text: 'A perfect drop gives bonus points. Three perfect drops in a row make your block wider again.', demo: DemoKind.watch, actor: Icons.star_rounded, target: Icons.stars_rounded),
    ],
  ),
  'starblaster': GameHowTo(
    name: 'Star Blaster',
    icon: Icons.rocket_launch_rounded,
    color: Color(0xFF3949AB),
    goal: 'Fly your ship, blast the enemy ships and survive as many waves as you can.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Survive the waves', text: 'Enemy ships come in waves. Shoot them for points and stay alive with your 3 lives.', demo: DemoKind.watch, actor: Icons.rocket_launch_rounded, target: Icons.gps_fixed_rounded),
      TutorialStep(title: 'Drag to fly', text: 'Put your finger anywhere on the screen and drag. Your ship follows and shoots by itself.', demo: DemoKind.drag, actor: Icons.rocket_launch_rounded, target: Icons.open_with_rounded, dx: 1, dy: 0),
      TutorialStep(title: 'Use the keyboard', text: 'On a computer you can fly with these keys. The arrow keys work too.', demo: DemoKind.keys, actor: Icons.rocket_launch_rounded, target: Icons.gps_fixed_rounded, keys: <String>['W', 'A', 'S', 'D'], pcOnly: true),
      TutorialStep(title: 'Dodge the enemies', text: 'Red ships fly straight, purple ones weave and orange ones shoot at you. Crashing into any of them costs a life.', demo: DemoKind.watch, actor: Icons.rocket_launch_rounded, target: Icons.warning_amber_rounded),
      TutorialStep(title: 'Grab power ups', text: 'Pick up the upgrades that drop. A weapon boost, a shield that blocks one hit, or a heart for an extra life.', demo: DemoKind.move, actor: Icons.rocket_launch_rounded, target: Icons.bolt_rounded),
    ],
  ),
  'sudoku': GameHowTo(
    name: 'Sudoku',
    icon: Icons.grid_on_rounded,
    color: Color(0xFF1E88E5),
    goal: 'Fill the grid so every row, column and box has the numbers 1 to 9 once.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Fill the grid', text: 'Every row, every column and every 3 by 3 box must have the numbers 1 to 9 with no repeats.', demo: DemoKind.watch, actor: Icons.grid_view_rounded, target: Icons.check_circle_rounded),
      TutorialStep(title: 'Pick a square', text: 'Tap an empty square, then tap a number at the bottom to put it in.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.numbers_rounded),
      TutorialStep(title: 'Mind your mistakes', text: 'A wrong number counts as a mistake. After 5 mistakes the game is over.', demo: DemoKind.watch, actor: Icons.warning_amber_rounded, target: Icons.heart_broken_rounded),
      TutorialStep(title: 'Use notes', text: 'Turn NOTES on to write small maybe numbers in a square. Turn it off to place a real number.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.edit_rounded),
      TutorialStep(title: 'Hint or undo', text: 'HINT fills one square but costs you points. UNDO takes back your last move. Finish fast with few hints for a high score.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.lightbulb_rounded),
    ],
  ),
  'survival': GameHowTo(
    name: 'Survival Shooter',
    icon: Icons.sports_martial_arts_rounded,
    color: Color(0xFFD84315),
    goal: 'Stay alive as long as you can while enemies keep coming.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Stay alive', text: 'Enemies keep coming and a new wave starts every 20 seconds. Keep your health bar from reaching zero.', demo: DemoKind.watch, actor: Icons.sports_martial_arts_rounded, target: Icons.favorite_rounded),
      TutorialStep(title: 'Drag the joystick', text: 'Drag the on screen joystick to run around the arena.', demo: DemoKind.drag, actor: Icons.control_camera_rounded, target: Icons.open_with_rounded, dx: -1, dy: 0.4),
      TutorialStep(title: 'Auto fire', text: 'You shoot by yourself at the closest enemy. You only need to move, not tap.', demo: DemoKind.watch, actor: Icons.sports_martial_arts_rounded, target: Icons.gps_fixed_rounded),
      TutorialStep(title: 'Keep moving', text: 'Enemies that touch you take away health. Run in circles and shoot as you go to score more.', demo: DemoKind.watch, actor: Icons.directions_run_rounded, target: Icons.stars_rounded),
    ],
  ),
  'targetgallery': GameHowTo(
    name: 'Target Gallery',
    icon: Icons.gps_fixed_rounded,
    color: Color(0xFFEF5350),
    goal: 'Shoot as many targets as you can in 60 seconds.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Hit the targets', text: 'Targets pop up around the range and disappear fast. You have 60 seconds to score.', demo: DemoKind.watch, actor: Icons.timer_rounded, target: Icons.gps_fixed_rounded),
      TutorialStep(title: 'Tap to shoot', text: 'Tap a target to shoot it. Small targets give more points and gold ones give the most.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.my_location_rounded),
      TutorialStep(title: 'Spare the blue ones', text: 'Blue smiling targets are friendly. Shooting one takes away 30 points and breaks your combo.', demo: DemoKind.watch, actor: Icons.warning_amber_rounded, target: Icons.block_rounded),
      TutorialStep(title: 'Build a combo', text: 'Every 3 hits in a row raise your multiplier, up to times 5. A missed shot resets it.', demo: DemoKind.watch, actor: Icons.local_fire_department_rounded, target: Icons.bolt_rounded),
      TutorialStep(title: 'Watch your ammo', text: 'You only have 6 shots, then you must reload for about a second. Tap RELOAD early when no targets are near.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.refresh_rounded),
    ],
  ),
  'towerdefense': GameHowTo(
    name: 'Tower Defense',
    icon: Icons.castle_rounded,
    color: Color(0xFF6D4C41),
    goal: 'Build towers to stop the enemies before they reach your base. Survive 30 waves.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Guard your base', text: 'Enemies walk along the path to your base. Each one that gets through costs you a life, and bosses cost 5.', demo: DemoKind.watch, actor: Icons.dangerous_rounded, target: Icons.castle_rounded),
      TutorialStep(title: 'Build a tower', text: 'Pick a tower type at the bottom, then tap an empty green square beside the path. Towers cost money.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.add_box_rounded),
      TutorialStep(title: 'Start the wave', text: 'Tap NEXT WAVE when you are ready. Beating enemies and waves earns you more money.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.play_arrow_rounded),
      TutorialStep(title: 'Upgrade or sell', text: 'Tap a tower to upgrade it up to level 3, or sell it to get most of your money back.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.upgrade_rounded),
      TutorialStep(title: 'Mix your towers', text: 'Arrow is cheap and fast. Cannon hits groups, Frost slows enemies and Sniper shoots very far. Use a mix.', demo: DemoKind.watch, actor: Icons.shield_rounded, target: Icons.stars_rounded),
    ],
  ),
  'trivia': GameHowTo(
    name: 'Trivia',
    icon: Icons.quiz_rounded,
    color: Color(0xFF8E24AA),
    goal: 'Answer 10 questions correctly and quickly to get the highest score.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Answer questions', text: 'You get a question and four answers. Try to get all 10 questions right.', demo: DemoKind.watch, actor: Icons.quiz_rounded, target: Icons.check_circle_rounded),
      TutorialStep(title: 'Tap your answer', text: 'Tap the answer you think is right. The game shows you if you were correct.', demo: DemoKind.choose, actor: Icons.touch_app_rounded, target: Icons.check_circle_rounded),
      TutorialStep(title: 'Beat the timer', text: 'You have 15 seconds for each question. If time runs out, you move on with no points.', demo: DemoKind.watch, actor: Icons.timer_rounded, target: Icons.hourglass_top_rounded),
      TutorialStep(title: 'Be quick', text: 'A right answer gives 10 points plus the seconds you have left. Fast answers score the most.', demo: DemoKind.watch, actor: Icons.speed_rounded, target: Icons.stars_rounded),
    ],
  ),
  'voidprotocols': GameHowTo(
    name: 'Void Protocols',
    icon: Icons.album_rounded,
    color: Color(0xFF5E35B1),
    goal: 'Fire one shot at a time and curve it around gravity wells to hit the target.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Hit the target', text: 'Each stage has a target. You fire one shot and it flies until it hits or misses.', demo: DemoKind.watch, actor: Icons.album_rounded, target: Icons.my_location_rounded),
      TutorialStep(title: 'Drag to aim', text: 'Drag on the field to point your shot. The plus and minus 5 degree buttons help you aim more exactly.', demo: DemoKind.drag, actor: Icons.gps_fixed_rounded, target: Icons.album_rounded, dx: 1, dy: -0.6),
      TutorialStep(title: 'Press FIRE', text: 'When you are lined up, tap FIRE. A missed shot lets you adjust and try again.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.rocket_launch_rounded),
      TutorialStep(title: 'Gravity wells', text: 'Wells pull your shot toward them or push it away. Tap a well button to switch between ATTRACT and REPEL.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.blur_on_rounded),
      TutorialStep(title: 'Use fewer tries', text: 'Look at where the wells bend your shot before you fire. Fewer attempts means a better run.', demo: DemoKind.watch, actor: Icons.visibility_rounded, target: Icons.stars_rounded),
    ],
  ),
  'weaponduel': GameHowTo(
    name: 'Weapon Duel',
    icon: Icons.gavel_rounded,
    color: Color(0xFFB71C1C),
    goal: 'Answer questions correctly to hit Ryan with your weapon until his health hits zero.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Beat Ryan', text: 'You and Ryan both start with health. Right answers hurt Ryan and wrong answers hurt you.', demo: DemoKind.watch, actor: Icons.sports_martial_arts_rounded, target: Icons.smart_toy_rounded),
      TutorialStep(title: 'Pick a weapon', text: 'Choose the War Hammer for bigger hits or the Swift Dagger for quicker, smaller hits.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.gavel_rounded),
      TutorialStep(title: 'Answer to attack', text: 'Tap the right answer within 10 seconds to strike. A wrong answer or running out of time lets Ryan hit you.', demo: DemoKind.choose, actor: Icons.touch_app_rounded, target: Icons.check_circle_rounded),
      TutorialStep(title: 'Build a combo', text: 'Right answers in a row make your hits stronger. A fast answer adds extra damage too.', demo: DemoKind.watch, actor: Icons.local_fire_department_rounded, target: Icons.bolt_rounded),
      TutorialStep(title: 'Use your shield', text: 'From level 9 you can pick a shield that blocks 3 hits. Save it for questions you are not sure about.', demo: DemoKind.watch, actor: Icons.shield_rounded, target: Icons.verified_user_rounded),
    ],
  ),
  'whot': GameHowTo(
    name: 'Whot',
    icon: Icons.casino_rounded,
    color: Color(0xFFC62828),
    goal: 'Be the first to play all your cards. Ryan is trying to do the same.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Empty your hand', text: 'You and Ryan take turns playing cards. The first one with no cards left wins.', demo: DemoKind.watch, actor: Icons.style_rounded, target: Icons.emoji_events_rounded),
      TutorialStep(title: 'Match the top card', text: 'Tap a card that has the same shape or the same number as the card on the pile. Cards you can play are lit up.', demo: DemoKind.move, actor: Icons.style_rounded, target: Icons.layers_rounded),
      TutorialStep(title: 'Cannot play? Draw', text: 'If no card fits, tap DRAW to take one from the deck. That ends your turn.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.add_circle_outline_rounded),
      TutorialStep(title: 'Special cards', text: '1 lets you go again. 2 makes Ryan pick two. 8 skips Ryan. 14 makes Ryan pick one card.', demo: DemoKind.watch, actor: Icons.bolt_rounded, target: Icons.style_rounded),
      TutorialStep(title: 'Use the Whot card', text: 'The Whot 20 card can go on anything, and then you call the shape you want next. Save it for when you are stuck.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.casino_rounded),
    ],
  ),
  'wordscramble': GameHowTo(
    name: 'Word Scramble',
    icon: Icons.sort_by_alpha_rounded,
    color: Color(0xFF00897B),
    goal: 'Unscramble the jumbled letters to spell the hidden word.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Fix the word', text: 'You see a word with its letters mixed up. Work out what the real word is.', demo: DemoKind.watch, actor: Icons.abc_rounded, target: Icons.spellcheck_rounded),
      TutorialStep(title: 'Type and check', text: 'Type the word in the box, then tap CHECK. You can skip a word you do not know.', demo: DemoKind.tap, actor: Icons.keyboard_rounded, target: Icons.check_circle_rounded),
      TutorialStep(title: 'Build a streak', text: 'A right word gives 10 points plus extra for each word you got right in a row. A wrong try resets the streak.', demo: DemoKind.watch, actor: Icons.local_fire_department_rounded, target: Icons.stars_rounded),
      TutorialStep(title: 'Use the clue', text: 'The game tells you how many letters the word has. Look for common endings to find the answer fast.', demo: DemoKind.watch, actor: Icons.lightbulb_rounded, target: Icons.spellcheck_rounded),
    ],
  ),
};
