import 'package:flutter/material.dart';
import 'how_to_model.dart';

const Map<String, GameHowTo> howToArenaB = <String, GameHowTo>{
  'dotsboxes': GameHowTo(
    name: 'Dots and Boxes',
    icon: Icons.grid_4x4_rounded,
    color: Color(0xFFFF6A00),
    goal: 'Close more boxes than Ryan.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Claim boxes', text: 'Win by closing more boxes than Ryan. A box is yours when you draw its 4th side.', demo: DemoKind.watch, actor: Icons.crop_square_rounded, target: Icons.check_box_rounded),
      TutorialStep(title: 'Draw a line', text: 'Tap the gap between two dots to draw a line there. You and Ryan take turns.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.remove_rounded),
      TutorialStep(title: 'Extra turn', text: 'When you close a box you go again. If you do not close one, it is Ryan\'s turn.', demo: DemoKind.watch, actor: Icons.check_box_rounded, target: Icons.replay_rounded),
      TutorialStep(title: 'Do not give gifts', text: 'Try not to draw the 3rd side of a box. That lets Ryan close it and score.', demo: DemoKind.watch, actor: Icons.warning_amber_rounded, target: Icons.crop_square_rounded),
    ],
  ),
  'dronebreach': GameHowTo(
    name: 'Drone Breach',
    icon: Icons.gps_fixed_rounded,
    color: Color(0xFF3DD6FF),
    goal: 'Shoot down the drone that carries the right answer.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Find the answer', text: 'A question shows at the top. Three drones fly down, each carrying an answer.', demo: DemoKind.watch, actor: Icons.quiz_rounded, target: Icons.gps_fixed_rounded),
      TutorialStep(title: 'Tap to shoot', text: 'Tap the drone with the correct answer to shoot it down and score 20 points.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.rocket_launch_rounded),
      TutorialStep(title: 'Do not miss', text: 'If the right drone gets past you, you lose a life. Shooting a wrong drone also costs a life.', demo: DemoKind.watch, actor: Icons.favorite_rounded, target: Icons.heart_broken_rounded),
      TutorialStep(title: 'Leave the wrong ones', text: 'Wrong drones are safe to ignore. You only have 3 lives, so read the question first.', demo: DemoKind.choose, actor: Icons.quiz_rounded, target: Icons.check_circle_rounded),
    ],
  ),
  'endlessrunner': GameHowTo(
    name: 'Signal Run',
    icon: Icons.directions_run_rounded,
    color: Color(0xFF3DDC84),
    goal: 'Run as far as you can, dodge blocks and grab the good tokens.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Keep running', text: 'You run down 3 lanes without stopping. Collect tokens to score and dodge the red blocks.', demo: DemoKind.watch, actor: Icons.directions_run_rounded, target: Icons.stars_rounded),
      TutorialStep(title: 'Swipe to switch', text: 'Swipe left or right anywhere on the screen to change lanes.', demo: DemoKind.swipe, actor: Icons.directions_run_rounded, target: Icons.swipe_rounded, dx: 1, dy: 0),
      TutorialStep(title: 'Or tap a lane', text: 'You can also tap a lane to jump straight into it.', demo: DemoKind.tap, actor: Icons.directions_run_rounded, target: Icons.touch_app_rounded),
      TutorialStep(title: 'Red blocks hurt', text: 'Running into a red block costs a life. You have 3 lives, then the run ends.', demo: DemoKind.watch, actor: Icons.favorite_rounded, target: Icons.dangerous_rounded),
      TutorialStep(title: 'Aim for answers', text: 'When tokens show answers, run into the correct one for bonus points. Plan your lane early.', demo: DemoKind.choose, actor: Icons.quiz_rounded, target: Icons.check_circle_rounded),
    ],
  ),
  'fruitslice': GameHowTo(
    name: 'Fruit Slice',
    icon: Icons.content_cut_rounded,
    color: Color(0xFFFF5A5F),
    goal: 'Slice as many fruits as you can without touching a bomb.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Slice the fruit', text: 'Fruit flies up from the bottom. Each fruit you slice scores a point.', demo: DemoKind.watch, actor: Icons.eco_rounded, target: Icons.content_cut_rounded),
      TutorialStep(title: 'Swipe across', text: 'Drag your finger across a fruit to cut it. Make a quick, straight swipe.', demo: DemoKind.swipe, actor: Icons.eco_rounded, target: Icons.content_cut_rounded, dx: 1, dy: -0.4),
      TutorialStep(title: 'Avoid bombs', text: 'If you slice a bomb, the game ends at once. Let bombs fall past you.', demo: DemoKind.watch, actor: Icons.dangerous_rounded, target: Icons.block_rounded),
      TutorialStep(title: 'Three lives', text: 'Every fruit you let fall costs a life. It gets faster the longer you play.', demo: DemoKind.watch, actor: Icons.favorite_rounded, target: Icons.heart_broken_rounded),
      TutorialStep(title: 'Go for combos', text: 'Slice 3 or more fruits in one swipe to earn a bonus.', demo: DemoKind.swipe, actor: Icons.local_fire_department_rounded, target: Icons.eco_rounded, dx: 1, dy: 0),
    ],
  ),
  'hangman': GameHowTo(
    name: 'Hangman',
    icon: Icons.spellcheck_rounded,
    color: Color(0xFFFFC940),
    goal: 'Guess the hidden word before you run out of lives.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Find the word', text: 'A secret word is hidden behind blank spaces. Guess it one letter at a time.', demo: DemoKind.watch, actor: Icons.abc_rounded, target: Icons.help_outline_rounded),
      TutorialStep(title: 'Tap a letter', text: 'Tap a letter on the screen. If it is in the word, it fills in the blanks.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.abc_rounded),
      TutorialStep(title: 'Seven lives', text: 'Each wrong letter costs a life. You have 7, and the word is lost when they are gone.', demo: DemoKind.watch, actor: Icons.favorite_rounded, target: Icons.heart_broken_rounded),
      TutorialStep(title: 'Score more', text: 'Every word you finish earns 10 points. Start with common letters like E and A.', demo: DemoKind.watch, actor: Icons.lightbulb_rounded, target: Icons.star_rounded),
    ],
  ),
  'jigsaw': GameHowTo(
    name: 'Jigsaw',
    icon: Icons.extension_rounded,
    color: Color(0xFF9B6BFF),
    goal: 'Put every piece in its place to finish the picture.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Build the picture', text: 'The pieces start in a pile below the board. Move them all onto the board to finish.', demo: DemoKind.watch, actor: Icons.extension_rounded, target: Icons.image_rounded),
      TutorialStep(title: 'Drag a piece', text: 'Press a piece and drag it onto the board.', demo: DemoKind.drag, actor: Icons.extension_rounded, target: Icons.grid_view_rounded, dx: 0, dy: -1),
      TutorialStep(title: 'It snaps in', text: 'Match the picture and the shapes. Drop a piece near its spot and it clicks in and locks.', demo: DemoKind.drag, actor: Icons.extension_rounded, target: Icons.lock_rounded, dx: 1, dy: -0.5),
      TutorialStep(title: 'Peek at it', text: 'Press and hold PREVIEW to see the finished picture while you work.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.visibility_rounded),
      TutorialStep(title: 'Be quick and neat', text: 'Your score goes down with time and extra moves. Place each piece carefully the first time.', demo: DemoKind.watch, actor: Icons.timer_rounded, target: Icons.star_rounded),
    ],
  ),
  'ludo': GameHowTo(
    name: 'Ludo',
    icon: Icons.casino_rounded,
    color: Color(0xFFFF6A00),
    goal: 'Be the first to bring all 4 of your tokens home.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Race home', text: 'Move your 4 tokens around the board and into home before Ryan does.', demo: DemoKind.watch, actor: Icons.token_rounded, target: Icons.home_rounded),
      TutorialStep(title: 'Roll the dice', text: 'Tap ROLL on your turn. You need a 6 to bring a token out of its starting area.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.casino_rounded),
      TutorialStep(title: 'Move a token', text: 'Tap a glowing token to move it forward by the number you rolled.', demo: DemoKind.move, actor: Icons.token_rounded, target: Icons.place_rounded),
      TutorialStep(title: 'Capture and bonus', text: 'Land on a rival token to send it back. A 6, a capture or reaching home gives you another roll.', demo: DemoKind.watch, actor: Icons.token_rounded, target: Icons.replay_rounded),
      TutorialStep(title: 'Watch out', text: 'Three 6s in a row lose your turn. Star squares and start squares keep your token safe.', demo: DemoKind.watch, actor: Icons.shield_rounded, target: Icons.star_rounded),
    ],
  ),
  'memory': GameHowTo(
    name: 'Memory Match',
    icon: Icons.style_rounded,
    color: Color(0xFF3DD6FF),
    goal: 'Find all 12 matching pairs in as few moves as you can.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Find the pairs', text: 'There are 24 cards face down. Every card has one twin hiding somewhere.', demo: DemoKind.watch, actor: Icons.style_rounded, target: Icons.copy_rounded),
      TutorialStep(title: 'Flip two cards', text: 'Tap a card to flip it, then tap a second card to try to match it.', demo: DemoKind.move, actor: Icons.style_rounded, target: Icons.style_rounded),
      TutorialStep(title: 'Match or hide', text: 'If the two cards match, they stay open. If not, they flip back after a moment, so remember them.', demo: DemoKind.watch, actor: Icons.check_circle_rounded, target: Icons.visibility_off_rounded),
      TutorialStep(title: 'Fewer moves wins', text: 'Your score is higher when you use fewer moves. Do not flip cards at random.', demo: DemoKind.watch, actor: Icons.psychology_rounded, target: Icons.star_rounded),
    ],
  ),
  'minesweeper': GameHowTo(
    name: 'Minesweeper',
    icon: Icons.flag_rounded,
    color: Color(0xFF3DDC84),
    goal: 'Open every safe square without tapping a mine.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Clear the field', text: 'The board hides 10 mines. Open all the safe squares to win.', demo: DemoKind.watch, actor: Icons.grid_view_rounded, target: Icons.dangerous_rounded),
      TutorialStep(title: 'Tap to open', text: 'Tap a square to open it. Opening a mine ends the game.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.grid_view_rounded),
      TutorialStep(title: 'Read the numbers', text: 'A number tells you how many mines touch that square, including corners. Use it to work out where mines are.', demo: DemoKind.watch, actor: Icons.numbers_rounded, target: Icons.dangerous_rounded),
      TutorialStep(title: 'Mark with a flag', text: 'Press and hold a square to place a flag where you think a mine is. A flagged square cannot be opened by accident.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.flag_rounded),
    ],
  ),
  'minicrossword': GameHowTo(
    name: 'Mini Crossword',
    icon: Icons.grid_on_rounded,
    color: Color(0xFFFFC940),
    goal: 'Fill the whole grid with the right letters.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Fill the grid', text: 'Read the clue, then fill in the letters of the word. Dark squares stay empty.', demo: DemoKind.watch, actor: Icons.grid_on_rounded, target: Icons.edit_rounded),
      TutorialStep(title: 'Tap and type', text: 'Tap a square, then type letters with the keyboard at the bottom. The clue shows above the grid.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.keyboard_rounded),
      TutorialStep(title: 'Across or down', text: 'Tap the same square twice to switch between the across word and the down word.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.swap_vert_rounded),
      TutorialStep(title: 'Get help', text: 'CHECK shows wrong letters in red. HINT reveals one letter. Both cost points.', demo: DemoKind.watch, actor: Icons.lightbulb_rounded, target: Icons.check_rounded),
      TutorialStep(title: 'Be fast', text: 'You start with 1500 points and lose some over time and for each check or hint. Finish quickly with few helps.', demo: DemoKind.watch, actor: Icons.timer_rounded, target: Icons.star_rounded),
    ],
  ),
  'numberduel': GameHowTo(
    name: 'Number Duel',
    icon: Icons.calculate_rounded,
    color: Color(0xFF3DD6FF),
    goal: 'Solve the sum before Ryan does.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Race Ryan', text: 'A maths question appears. Answer it before Ryan to win the point.', demo: DemoKind.watch, actor: Icons.calculate_rounded, target: Icons.bolt_rounded),
      TutorialStep(title: 'Type and send', text: 'Type your answer in the box, then tap SUBMIT or press enter on the keyboard.', demo: DemoKind.tap, actor: Icons.keyboard_rounded, target: Icons.send_rounded),
      TutorialStep(title: 'Wrong is fine', text: 'If your answer is wrong, the box clears and you can try again. But Ryan is still racing you.', demo: DemoKind.watch, actor: Icons.close_rounded, target: Icons.replay_rounded),
      TutorialStep(title: 'Be quick', text: 'Ryan answers in about 2 to 4 seconds. Go for the easy parts of the sum first in your head.', demo: DemoKind.watch, actor: Icons.timer_rounded, target: Icons.emoji_events_rounded),
    ],
  ),
  'pinball': GameHowTo(
    name: 'Pinball',
    icon: Icons.album_rounded,
    color: Color(0xFFFF5A5F),
    goal: 'Keep the ball alive and rack up a high score.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Launch the ball', text: 'Tap the table to fire the ball up the right-hand lane. You get 3 balls.', demo: DemoKind.tap, actor: Icons.album_rounded, target: Icons.rocket_launch_rounded),
      TutorialStep(title: 'Use the flippers', text: 'Touch the left half of the table for the left flipper and the right half for the right flipper.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.album_rounded),
      TutorialStep(title: 'Time your tap', text: 'Tap just as the ball arrives at a flipper to knock it back up.', demo: DemoKind.watch, actor: Icons.album_rounded, target: Icons.timer_rounded),
      TutorialStep(title: 'Hit the bumpers', text: 'Round bumpers kick the ball and score 100 points each.', demo: DemoKind.watch, actor: Icons.album_rounded, target: Icons.blur_circular_rounded),
      TutorialStep(title: 'Light the lanes', text: 'Roll through all 3 top lanes for a 1000 point bonus and a bigger multiplier, up to x5. You get one free save if you lose the ball in the first 6 seconds.', demo: DemoKind.watch, actor: Icons.album_rounded, target: Icons.stars_rounded),
    ],
  ),
  'pool': GameHowTo(
    name: '8 Ball Pool',
    icon: Icons.sports_baseball_rounded,
    color: Color(0xFF3DDC84),
    goal: 'Pocket all your balls, then sink the black 8 ball before Ryan.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Beat Ryan', text: 'Pocket all the balls in your group, then sink the black 8 ball to win.', demo: DemoKind.watch, actor: Icons.sports_baseball_rounded, target: Icons.emoji_events_rounded),
      TutorialStep(title: 'Pull back to shoot', text: 'Put your finger on the table and pull away from the white ball like a slingshot. It shoots the other way.', demo: DemoKind.drag, actor: Icons.sports_baseball_rounded, target: Icons.my_location_rounded, dx: -1, dy: 0),
      TutorialStep(title: 'Power and aim', text: 'The further you pull, the harder the shot. Let go to shoot.', demo: DemoKind.drag, actor: Icons.touch_app_rounded, target: Icons.speed_rounded, dx: -1, dy: 0.4),
      TutorialStep(title: 'Pick your group', text: 'The first ball you pocket decides if you have solids (1 to 7) or stripes (9 to 15). Keep potting yours to keep your turn.', demo: DemoKind.watch, actor: Icons.sports_baseball_rounded, target: Icons.check_circle_rounded),
      TutorialStep(title: 'Fouls and the 8', text: 'Sinking the white ball or hitting nothing is a foul, and Ryan places the white anywhere. Sink the 8 ball too early and you lose.', demo: DemoKind.watch, actor: Icons.warning_amber_rounded, target: Icons.circle),
    ],
  ),
  'puzzlerush': GameHowTo(
    name: 'Puzzle Rush',
    icon: Icons.castle_rounded,
    color: Color(0xFF9B6BFF),
    goal: 'Solve as many chess puzzles as you can before time runs out.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Solve puzzles', text: 'Each puzzle is a chess position. Find the best move for your side, like a checkmate or winning a piece.', demo: DemoKind.watch, actor: Icons.psychology_rounded, target: Icons.castle_rounded),
      TutorialStep(title: 'Tap to move', text: 'Tap one of your pieces, then tap the square you want to move it to.', demo: DemoKind.move, actor: Icons.castle_rounded, target: Icons.crop_square_rounded),
      TutorialStep(title: 'Replies', text: 'Some puzzles go on after the other side replies. Keep finding the best move until it is solved.', demo: DemoKind.watch, actor: Icons.swap_horiz_rounded, target: Icons.check_circle_rounded),
      TutorialStep(title: '3 minutes, 3 strikes', text: 'You have 3 minutes. A wrong move costs a strike, and 3 strikes ends the run.', demo: DemoKind.watch, actor: Icons.timer_rounded, target: Icons.heart_broken_rounded),
      TutorialStep(title: 'Daily set', text: 'Everyone gets the same puzzles each day. Think before you tap so you do not waste strikes.', demo: DemoKind.watch, actor: Icons.today_rounded, target: Icons.emoji_events_rounded),
    ],
  ),
  'reaction': GameHowTo(
    name: 'Reaction Test',
    icon: Icons.bolt_rounded,
    color: Color(0xFF3DDC84),
    goal: 'Tap as fast as you can the moment the screen turns green.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Wait for green', text: 'The screen starts off waiting. Do not tap yet.', demo: DemoKind.watch, actor: Icons.hourglass_top_rounded, target: Icons.circle),
      TutorialStep(title: 'Tap on green', text: 'The moment the screen turns green, tap it as fast as you can.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.flash_on_rounded),
      TutorialStep(title: 'Do not jump early', text: 'If you tap before green, that round does not count and you must wait again.', demo: DemoKind.watch, actor: Icons.block_rounded, target: Icons.timer_off_rounded),
      TutorialStep(title: 'Five rounds', text: 'Your average time over 5 rounds is your score. A faster average gives a higher score.', demo: DemoKind.watch, actor: Icons.speed_rounded, target: Icons.star_rounded),
    ],
  ),
  'reversi': GameHowTo(
    name: 'Reversi',
    icon: Icons.circle_outlined,
    color: Color(0xFF3399FF),
    goal: 'Have more pieces than Ryan when the game ends.',
    steps: <TutorialStep>[
      TutorialStep(title: 'Own more pieces', text: 'You play black and Ryan plays blue. Whoever has more pieces at the end wins.', demo: DemoKind.watch, actor: Icons.circle, target: Icons.emoji_events_rounded),
      TutorialStep(title: 'Place a piece', text: 'Tap a square with a small white dot. Those are the only squares where you can play.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.add_circle_outline_rounded),
      TutorialStep(title: 'Flip to win', text: 'Trap Ryan pieces in a straight line between your new piece and another of yours. They all flip to your colour.', demo: DemoKind.move, actor: Icons.circle, target: Icons.swap_horiz_rounded),
      TutorialStep(title: 'Grab the corners', text: 'Corner pieces can never be flipped. Try to take them, and do not rush to flip too many early.', demo: DemoKind.watch, actor: Icons.lightbulb_rounded, target: Icons.crop_square_rounded),
    ],
  ),
  'rps': GameHowTo(
    name: 'Rock Paper Scissors',
    icon: Icons.back_hand_rounded,
    color: Color(0xFFFF6A00),
    goal: 'Win 3 rounds before Ryan does.',
    steps: <TutorialStep>[
      TutorialStep(title: 'First to 3', text: 'You and Ryan play rounds. The first to win 3 rounds wins the match.', demo: DemoKind.watch, actor: Icons.back_hand_rounded, target: Icons.emoji_events_rounded),
      TutorialStep(title: 'Pick a move', text: 'Tap Rock, Paper or Scissors. Ryan picks at the same time.', demo: DemoKind.tap, actor: Icons.touch_app_rounded, target: Icons.back_hand_rounded),
      TutorialStep(title: 'Who beats who', text: 'Rock beats scissors, scissors beats paper, and paper beats rock. The same pick is a draw.', demo: DemoKind.watch, actor: Icons.content_cut_rounded, target: Icons.description_rounded),
      TutorialStep(title: 'Mix it up', text: 'Do not use the same move every time. Ryan picks at random, so just stay unpredictable and enjoy it.', demo: DemoKind.watch, actor: Icons.swap_horiz_rounded, target: Icons.star_rounded),
    ],
  ),
};
